EzBus: src/common/ezbus_log.h File Reference
ezbus_log.h File Reference
#include <ezbus_platform.h>
Functions
void ezbus_log (int level, char *fmt,...)
Function Documentation
void ezbus_log (int level, char * fmt, ...)
Definition at line 25 of file ezbus_log.c.
References EZBUS_LOG_STREAM.
Referenced by ezbus_address_init(), ezbus_hex_dump(), ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_arbiter_receive_signal_token(), ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_coldboot_signal_dominant(), ezbus_mac_coldboot_signal_silent_stop(), ezbus_mac_coldboot_signal_start(), ezbus_mac_coldboot_signal_stop(), ezbus_mac_peers_clear(), ezbus_mac_peers_log(), ezbus_mac_receiver_signal_fault(), ezbus_mac_receiver_signal_full(), ezbus_mac_receiver_signal_wait(), ezbus_mac_token_signal_expired(), ezbus_mac_transmitter_run(), ezbus_mac_transmitter_signal_empty(), ezbus_mac_transmitter_signal_fault(), ezbus_mac_transmitter_signal_full(), ezbus_mac_transmitter_signal_sent(), ezbus_mac_transmitter_signal_wait(), ezbus_mac_warmboot_signal_finished(), ezbus_mac_warmboot_signal_start(), ezbus_mac_warmboot_signal_stop(), ezbus_port_receiver_fault(), ezbus_port_receiver_ready(), ezbus_port_transmitter_ack(), ezbus_port_transmitter_empty(), ezbus_port_transmitter_fault(), ezbus_port_transmitter_limit(), ezbus_port_transmitter_resend(), ezbus_socket_callback_receiver_fault(), ezbus_socket_callback_transmitter_ack(), ezbus_socket_callback_transmitter_fault(), ezbus_socket_callback_transmitter_limit(), ezbus_socket_callback_transmitter_resend(), ezbus_timer_run(), and ezbuz_mac_arbiter_transmit_token().