EzBus: src/mac/ezbus_mac_arbiter.c File Reference
ezbus_mac_arbiter.c File Reference
#include <ezbus_mac_arbiter.h>
#include <ezbus_mac_arbiter_transmit.h>
#include <ezbus_mac_arbiter_receive.h>
#include <ezbus_mac_transmitter.h>
#include <ezbus_mac_receiver.h>
#include <ezbus_mac_token.h>
#include <ezbus_mac_coldboot.h>
#include <ezbus_mac_warmboot.h>
#include <ezbus_mac_peers.h>
#include <ezbus_socket_callback.h>
#include <ezbus_crc.h>
#include <ezbus_hex.h>
#include <ezbus_log.h>
Functions
void ezbus_mac_arbiter_init (ezbus_mac_t *mac)
void ezbus_mac_arbiter_run (ezbus_mac_t *mac)
uint16_t ezbus_mac_arbiter_get_token_age (ezbus_mac_t *mac)
void ezbus_mac_arbiter_set_token_age (ezbus_mac_t *mac, uint16_t age)
void ezbus_mac_arbiter_set_state (ezbus_mac_t *mac, ezbus_mac_arbiter_state_t state)
ezbus_mac_arbiter_state_t ezbus_mac_arbiter_get_state (ezbus_mac_t *mac)
uint8_t ezbus_mac_arbiter_get_warmboot_cycles (ezbus_mac_t *mac)
void ezbus_mac_arbiter_set_warmboot_cycles (ezbus_mac_t *mac, uint8_t cycles)
void ezbus_mac_arbiter_dec_warmboot_cycles (ezbus_mac_t *mac)
void ezbus_mac_arbiter_rst_warmboot_cycles (ezbus_mac_t *mac)
void ezbus_mac_arbiter_receive_signal_token (ezbus_mac_t *mac, ezbus_packet_t *packet)
A give-token packet has been received.
void ezbus_mac_arbiter_receive_signal_parcel (ezbus_mac_t *mac, ezbus_packet_t *packet)
void ezbus_mac_warmboot_signal_finished (ezbus_mac_t *mac)
void ezbus_mac_token_signal_expired (ezbus_mac_t *mac)
Function Documentation
void ezbus_mac_arbiter_dec_warmboot_cycles (ezbus_mac_t * mac)
Definition at line 122 of file ezbus_mac_arbiter.c.
References ezbus_mac_get_arbiter(), and _ezbus_mac_arbiter_t::warmboot_cycles.
Referenced by ezbus_mac_warmboot_get_state().
ezbus_mac_arbiter_state_t ezbus_mac_arbiter_get_state (ezbus_mac_t * mac)
Definition at line 104 of file ezbus_mac_arbiter.c.
References ezbus_mac_get_arbiter(), and _ezbus_mac_arbiter_t::state.
Referenced by ezbus_mac_arbiter_receive_signal_token(), and ezbus_mac_arbiter_run().
uint16_t ezbus_mac_arbiter_get_token_age (ezbus_mac_t * mac)
Definition at line 85 of file ezbus_mac_arbiter.c.
References ezbus_mac_get_arbiter(), and _ezbus_mac_arbiter_t::token_age.
Referenced by ezbuz_mac_arbiter_transmit_token().
uint8_t ezbus_mac_arbiter_get_warmboot_cycles (ezbus_mac_t * mac)
Definition at line 110 of file ezbus_mac_arbiter.c.
References ezbus_mac_get_arbiter(), and _ezbus_mac_arbiter_t::warmboot_cycles.
Referenced by ezbus_mac_warmboot_get_state().
void ezbus_mac_arbiter_init (ezbus_mac_t * mac)
Definition at line 48 of file ezbus_mac_arbiter.c.
References ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_mac_arbiter_set_state(), ezbus_mac_get_arbiter(), and mac_arbiter_state_offline.
Referenced by ezbus_mac_init().
void ezbus_mac_arbiter_receive_signal_parcel (ezbus_mac_t * mac, ezbus_packet_t * packet)
BEGIN RECEIVE PARCEL
Definition at line 274 of file ezbus_mac_arbiter.c.
References ezbus_address_compare(), ezbus_address_copy(), ezbus_log(), EZBUS_LOG_RECEIVER, ezbus_mac_get_arbiter(), ezbus_mac_get_receiver_packet(), ezbus_mac_transmitter_put(), ezbus_packet_dst(), ezbus_packet_dst_socket(), ezbus_packet_init(), ezbus_packet_seq(), ezbus_packet_set_dst(), ezbus_packet_set_dst_socket(), ezbus_packet_set_seq(), ezbus_packet_set_src(), ezbus_packet_set_src_socket(), ezbus_packet_set_type(), ezbus_packet_src(), ezbus_packet_src_socket(), ezbus_self_address, ezbus_socket_callback_receiver_ready(), packet_type_ack, _ezbus_mac_arbiter_t::rx_ack_address, _ezbus_mac_arbiter_t::rx_ack_pend, and _ezbus_mac_arbiter_t::rx_ack_seq.
Referenced by ezbus_mac_arbiter_receive_run().
void ezbus_mac_arbiter_receive_signal_token (ezbus_mac_t * mac, ezbus_packet_t * packet)
A give-token packet has been received.
Definition at line 228 of file ezbus_mac_arbiter.c.
References ezbus_address_compare(), ezbus_crc_equal(), ezbus_log(), EZBUS_LOG_TOKEN, ezbus_mac_arbiter_get_state(), ezbus_mac_arbiter_set_state(), ezbus_mac_arbiter_set_token_age(), ezbus_mac_peers_crc(), ezbus_mac_token_acquire(), ezbus_mac_token_reset(), ezbus_packet_dst(), ezbus_packet_get_token_age(), ezbus_packet_get_token_crc(), ezbus_self_address, EZBUS_WARMBOOT_AGE, mac_arbiter_state_online, mac_arbiter_state_reboot_warm, and mac_arbiter_state_service_start.
Referenced by ezbus_mac_arbiter_receive_run().
void ezbus_mac_arbiter_rst_warmboot_cycles (ezbus_mac_t * mac)
Definition at line 132 of file ezbus_mac_arbiter.c.
References ezbus_address_copy(), ezbus_broadcast_address, ezbus_log(), EZBUS_LOG_ARBITER, EZBUS_LOG_ONLINE, ezbus_mac_arbiter_set_state(), ezbus_mac_arbiter_transmit_busy(), ezbus_mac_coldboot_reset, ezbus_mac_coldboot_set_state(), ezbus_mac_get_arbiter(), ezbus_mac_peers_clear(), ezbus_mac_token_acquired(), ezbus_mac_token_relinquish(), ezbus_mac_token_reset(), ezbus_mac_transmitter_empty, ezbus_mac_warmboot_set_state(), ezbus_socket_callback_transmitter_empty(), EZBUS_WARMBOOT_CYCLES, ezbuz_mac_arbiter_transmit_token(), mac_arbiter_state_offline, mac_arbiter_state_online, _ezbus_mac_arbiter_t::rx_ack_address, _ezbus_mac_arbiter_t::rx_ack_pend, _ezbus_mac_arbiter_t::rx_ack_seq, state_coldboot_start, state_warmboot_idle, state_warmboot_start, and _ezbus_mac_arbiter_t::warmboot_cycles.
Referenced by ezbus_mac_arbiter_init(), and ezbus_mac_warmboot_signal_finished().
void ezbus_mac_arbiter_run (ezbus_mac_t * mac)
Definition at line 57 of file ezbus_mac_arbiter.c.
References ezbus_mac_arbiter_get_state(), mac_arbiter_state_coldboot, mac_arbiter_state_offline, mac_arbiter_state_online, mac_arbiter_state_reboot_cold, mac_arbiter_state_reboot_warm, mac_arbiter_state_service_start, and mac_arbiter_state_warmboot.
Referenced by ezbus_mac_run().
void ezbus_mac_arbiter_set_state (ezbus_mac_t * mac, ezbus_mac_arbiter_state_t state)
Definition at line 98 of file ezbus_mac_arbiter.c.
References ezbus_mac_get_arbiter(), and _ezbus_mac_arbiter_t::state.
Referenced by ezbus_mac_arbiter_init(), ezbus_mac_arbiter_receive_signal_token(), ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_mac_coldboot_signal_dominant(), ezbus_mac_coldboot_signal_start(), ezbus_mac_token_signal_expired(), and ezbus_mac_warmboot_signal_finished().
void ezbus_mac_arbiter_set_token_age (ezbus_mac_t * mac, uint16_t age)
Definition at line 91 of file ezbus_mac_arbiter.c.
References ezbus_mac_get_arbiter(), and _ezbus_mac_arbiter_t::token_age.
Referenced by ezbus_mac_arbiter_receive_signal_token().
void ezbus_mac_arbiter_set_warmboot_cycles (ezbus_mac_t * mac, uint8_t cycles)
Definition at line 116 of file ezbus_mac_arbiter.c.
References ezbus_mac_get_arbiter(), and _ezbus_mac_arbiter_t::warmboot_cycles.
void ezbus_mac_token_signal_expired (ezbus_mac_t * mac)
Definition at line 334 of file ezbus_mac_arbiter.c.
References ezbus_log(), EZBUS_LOG_TOKEN, ezbus_mac_arbiter_set_state(), and mac_arbiter_state_reboot_warm.
Referenced by ezbus_mac_token_acquired().
void ezbus_mac_warmboot_signal_finished (ezbus_mac_t * mac)
END RECEIVE PARCEL
Definition at line 318 of file ezbus_mac_arbiter.c.
References ezbus_log(), EZBUS_LOG_WARMBOOT, ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_mac_arbiter_set_state(), ezbus_mac_token_acquire(), ezbus_mac_token_reset(), ezbus_mac_warmboot_set_state(), mac_arbiter_state_service_start, and state_warmboot_start.
Referenced by ezbus_mac_warmboot_get_state().