EzBus: src/platform/ezbus_platform_caribou.c File Reference
ezbus_platform_caribou.c File Reference
#include <ezbus_platform_caribou.h>
#include <ezbus_address.h>
#include <caribou/lib/stdio.h>
#include <caribou/dev/uart.h>
#include <caribou/lib/heap.h>
#include <caribou/lib/rand.h>
#include <caribou/lib/uuid.h>
Functions
int ezbus_platform_open (ezbus_platform_port_t *port, uint32_t speed)
int ezbus_platform_send (ezbus_platform_port_t *port, void *bytes, size_t size)
int ezbus_platform_recv (ezbus_platform_port_t *port, void *bytes, size_t size)
int ezbus_platform_getc (ezbus_platform_port_t *port)
void ezbus_platform_close (ezbus_platform_port_t *port)
void ezbus_platform_drain (ezbus_platform_port_t *port)
int ezbus_platform_set_speed (ezbus_platform_port_t *port, uint32_t speed)
void ezbus_platform_flush (ezbus_platform_port_t *port)
void * ezbus_platform_memset (void *dest, int c, size_t n)
void * ezbus_platform_memcpy (void *dest, const void *src, size_t n)
void * ezbus_platform_memmove (void *dest, const void *src, size_t n)
int ezbus_platform_memcmp (const void *dest, const void *src, size_t n)
char * ezbus_platform_strcpy (char *dest, const char *src)
char * ezbus_platform_strcat (char *dest, const char *src)
char * ezbus_platform_strncpy (char *dest, const char *src, size_t n)
size_t ezbus_platform_strlen (const char *s)
void * ezbus_platform_malloc (size_t n)
void * ezbus_platform_realloc (void *src, size_t n)
void ezbus_platform_free (void *src)
ezbus_ms_tick_t ezbus_platform_get_ms_ticks ()
int ezbus_platform_rand (void)
void ezbus_platform_srand (unsigned int seed)
int ezbus_platform_random (int lower, int upper)
void ezbus_platform_rand_init (void)
void ezbus_platform_delay (unsigned int ms)
void ezbus_platform_set_address (void *address, size_t size)
void ezbus_platform_address (void *address)
void ezbus_platform_port_dump (ezbus_platform_port_t *platform_port, const char *prefix)
Function Documentation
void ezbus_platform_address (void * address)
Definition at line 187 of file ezbus_platform_caribou.c.
References ezbus_address_t::word.
void ezbus_platform_close (ezbus_platform_port_t * port)
Definition at line 66 of file ezbus_platform_caribou.c.
References ezbus_platform_port_t::fd.
void ezbus_platform_delay (unsigned int ms)
Definition at line 173 of file ezbus_platform_caribou.c.
References ezbus_platform_get_ms_ticks().
void ezbus_platform_drain (ezbus_platform_port_t * port)
Definition at line 71 of file ezbus_platform_caribou.c.
References ezbus_platform_getc().
void ezbus_platform_flush (ezbus_platform_port_t * port)
Definition at line 87 of file ezbus_platform_caribou.c.
References ezbus_platform_port_t::fd.
void ezbus_platform_free (void * src)
Definition at line 142 of file ezbus_platform_caribou.c.
ezbus_ms_tick_t ezbus_platform_get_ms_ticks ()
Definition at line 147 of file ezbus_platform_caribou.c.
Referenced by ezbus_platform_delay(), and ezbus_platform_rand_init().
int ezbus_platform_getc (ezbus_platform_port_t * port)
Definition at line 60 of file ezbus_platform_caribou.c.
References ezbus_platform_port_t::fd.
Referenced by ezbus_platform_drain().
void* ezbus_platform_malloc (size_t n)
Definition at line 132 of file ezbus_platform_caribou.c.
int ezbus_platform_memcmp (const void * dest, const void * src, size_t n)
Definition at line 107 of file ezbus_platform_caribou.c.
void* ezbus_platform_memcpy (void * dest, const void * src, size_t n)
Definition at line 97 of file ezbus_platform_caribou.c.
Referenced by ezbus_platform_set_address().
void* ezbus_platform_memmove (void * dest, const void * src, size_t n)
Definition at line 102 of file ezbus_platform_caribou.c.
void* ezbus_platform_memset (void * dest, int c, size_t n)
Definition at line 92 of file ezbus_platform_caribou.c.
int ezbus_platform_open (ezbus_platform_port_t * port, uint32_t speed)
Definition at line 32 of file ezbus_platform_caribou.c.
References ezbus_platform_set_speed(), ezbus_platform_port_t::fd, and ezbus_platform_port_t::serial_port_no.
void ezbus_platform_port_dump (ezbus_platform_port_t * platform_port, const char * prefix)
Definition at line 199 of file ezbus_platform_caribou.c.
Referenced by ezbus_port_dump().
int ezbus_platform_rand (void)
Definition at line 152 of file ezbus_platform_caribou.c.
void ezbus_platform_rand_init (void)
Definition at line 168 of file ezbus_platform_caribou.c.
References ezbus_platform_get_ms_ticks(), and ezbus_platform_srand().
int ezbus_platform_random (int lower, int upper)
Definition at line 162 of file ezbus_platform_caribou.c.
void* ezbus_platform_realloc (void * src, size_t n)
Definition at line 137 of file ezbus_platform_caribou.c.
int ezbus_platform_recv (ezbus_platform_port_t * port, void * bytes, size_t size)
Definition at line 54 of file ezbus_platform_caribou.c.
References ezbus_platform_port_t::fd.
int ezbus_platform_send (ezbus_platform_port_t * port, void * bytes, size_t size)
Definition at line 42 of file ezbus_platform_caribou.c.
References ezbus_platform_port_t::fd.
void ezbus_platform_set_address (void * address, size_t size)
Definition at line 182 of file ezbus_platform_caribou.c.
References ezbus_platform_memcpy().
int ezbus_platform_set_speed (ezbus_platform_port_t * port, uint32_t speed)
Definition at line 76 of file ezbus_platform_caribou.c.
References ezbus_platform_port_t::dir_pin, and ezbus_platform_port_t::serial_port_no.
Referenced by ezbus_platform_open().
void ezbus_platform_srand (unsigned int seed)
Definition at line 157 of file ezbus_platform_caribou.c.
Referenced by ezbus_platform_rand_init().
char* ezbus_platform_strcat (char * dest, const char * src)
Definition at line 117 of file ezbus_platform_caribou.c.
char* ezbus_platform_strcpy (char * dest, const char * src)
Definition at line 112 of file ezbus_platform_caribou.c.
size_t ezbus_platform_strlen (const char * s)
Definition at line 127 of file ezbus_platform_caribou.c.
char* ezbus_platform_strncpy (char * dest, const char * src, size_t n)
Definition at line 122 of file ezbus_platform_caribou.c.