EzBus: src/mac/ezbus_mac_arbiter_receive.c File Reference
ezbus_mac_arbiter_receive.c File Reference
#include <ezbus_mac_arbiter_receive.h>
#include <ezbus_mac_arbiter_transmit.h>
#include <ezbus_mac_transmitter.h>
#include <ezbus_mac_receiver.h>
#include <ezbus_mac_coldboot.h>
#include <ezbus_mac_warmboot.h>
#include <ezbus_mac_token.h>
#include <ezbus_mac_peers.h>
#include <ezbus_socket_callback.h>
#include <ezbus_address.h>
#include <ezbus_packet.h>
#include <ezbus_peer.h>
#include <ezbus_hex.h>
#include <ezbus_log.h>
Functions
void ezbus_mac_arbiter_receive_init (ezbus_mac_t *mac)
void ezbus_mac_arbiter_receive_run (ezbus_mac_t *mac)
void ezbus_mac_receiver_signal_full (ezbus_mac_t *mac)
void ezbus_mac_receiver_signal_empty (ezbus_mac_t *mac)
void ezbus_mac_receiver_signal_ack (ezbus_mac_t *mac)
void ezbus_mac_receiver_signal_wait (ezbus_mac_t *mac)
void ezbus_mac_receiver_signal_fault (ezbus_mac_t *mac)
Function Documentation
void ezbus_mac_arbiter_receive_init (ezbus_mac_t * mac)
Definition at line 54 of file ezbus_mac_arbiter_receive.c.
References _ezbus_mac_arbiter_receive_t::ack_rx_timer, ezbus_mac_get_arbiter_receive(), ezbus_mac_token_ring_time(), ezbus_timer_init(), ezbus_timer_set_callback(), ezbus_timer_set_key(), ezbus_timer_set_period(), and _ezbus_mac_arbiter_receive_t::warmboot_timer.
Referenced by ezbus_mac_init().
void ezbus_mac_arbiter_receive_run (ezbus_mac_t * mac)
Definition at line 69 of file ezbus_mac_arbiter_receive.c.
References _ezbus_mac_arbiter_receive_t::ack_rx_timer, _ezbus_mac_coldboot_t::coldboot_timer, ezbus_address_compare(), ezbus_address_string(), ezbus_broadcast_address, ezbus_log(), EZBUS_LOG_ARBITER, EZBUS_LOG_BOOTSTATE, ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_arbiter_receive_signal_token(), ezbus_mac_arbiter_transmit_reset(), ezbus_mac_coldboot_get_state(), ezbus_mac_coldboot_set_state(), ezbus_mac_get_arbiter_receive(), ezbus_mac_get_coldboot(), ezbus_mac_get_receiver_packet(), ezbus_mac_get_transmitter_packet(), ezbus_mac_peers_insort(), ezbus_mac_peers_log(), ezbus_mac_token_acquired(), ezbus_mac_token_relinquish(), ezbus_mac_transmitter_put(), ezbus_mac_transmitter_set_state(), ezbus_mac_warmboot_set_state(), ezbus_packet_dst(), ezbus_packet_init(), ezbus_packet_seq(), ezbus_packet_set_dst(), ezbus_packet_set_dst_socket(), ezbus_packet_set_seq(), ezbus_packet_set_src(), ezbus_packet_set_src_socket(), ezbus_packet_set_type(), ezbus_packet_src(), ezbus_peer_init(), ezbus_platform_random(), ezbus_self_address, EZBUS_SOCKET_ANY, ezbus_socket_callback_transmitter_ack(), ezbus_socket_callback_transmitter_fault(), ezbus_timer_restart, ezbus_timer_run(), ezbus_timer_set_period(), ezbus_timer_stop, EZBUS_WARMBOOT_TIMER_MAX, EZBUS_WARMBOOT_TIMER_MIN, packet_type_warmboot_ak, packet_type_warmboot_rp, state_coldboot_silent_start, state_coldboot_silent_stop, state_warmboot_idle, transmitter_state_send, _ezbus_mac_arbiter_receive_t::warmboot_seq, and _ezbus_mac_arbiter_receive_t::warmboot_timer.
Referenced by ezbus_mac_run().
void ezbus_mac_receiver_signal_ack (ezbus_mac_t * mac)
Definition at line 327 of file ezbus_mac_arbiter_receive.c.
void ezbus_mac_receiver_signal_empty (ezbus_mac_t * mac)
Definition at line 322 of file ezbus_mac_arbiter_receive.c.
Referenced by ezbus_mac_receiver_get().
void ezbus_mac_receiver_signal_fault (ezbus_mac_t * mac)
Definition at line 340 of file ezbus_mac_arbiter_receive.c.
References EZBUS_ERR_NOTREADY, ezbus_fault_str(), ezbus_log(), EZBUS_LOG_RECEIVER, and ezbus_mac_receiver_get_err().
Referenced by ezbus_mac_receiver_get().
void ezbus_mac_receiver_signal_full (ezbus_mac_t * mac)
Definition at line 295 of file ezbus_mac_arbiter_receive.c.
References ezbus_log(), EZBUS_LOG_RECEIVER, ezbus_mac_coldboot_reset, ezbus_mac_get_receiver_packet(), ezbus_mac_peers_log(), ezbus_packet_type(), packet_type_ack, packet_type_coldboot, packet_type_give_token, packet_type_nack, packet_type_parcel, packet_type_reset, packet_type_speed, packet_type_take_token, packet_type_warmboot_ak, packet_type_warmboot_rp, and packet_type_warmboot_rq.
Referenced by ezbus_mac_receiver_get().
void ezbus_mac_receiver_signal_wait (ezbus_mac_t * mac)
Definition at line 331 of file ezbus_mac_arbiter_receive.c.
References ezbus_log(), EZBUS_LOG_RECEIVER, ezbus_mac_receiver_set_state(), ezbus_mac_transmitter_empty, and receiver_state_empty.