EzBus: src/mac/ezbus_mac_arbiter_transmit.h File Reference
ezbus_mac_arbiter_transmit.h File Reference
#include <ezbus_mac_arbiter.h>
#include <ezbus_mac.h>
#include <ezbus_timer.h>
#include <ezbus_packet.h>
Classes
struct _ezbus_mac_arbiter_transmit_t
Typedefs
typedef struct _ezbus_mac_arbiter_transmit_t ezbus_mac_arbiter_transmit_t
Functions
void ezbus_mac_arbiter_transmit_init (ezbus_mac_t *mac)
void ezbus_mac_arbiter_transmit_run (ezbus_mac_t *mac)
void ezbuz_mac_arbiter_transmit_token (ezbus_mac_t *mac)
bool ezbus_mac_arbiter_transmit_busy (ezbus_mac_t *mac)
void ezbus_mac_arbiter_transmit_reset (ezbus_mac_t *mac)
Typedef Documentation
typedef struct _ezbus_mac_arbiter_transmit_t ezbus_mac_arbiter_transmit_t
Function Documentation
bool ezbus_mac_arbiter_transmit_busy (ezbus_mac_t * mac)
Definition at line 205 of file ezbus_mac_arbiter_transmit.c.
References _ezbus_mac_arbiter_transmit_t::ack_tx_count, and ezbus_mac_get_arbiter_transmit().
Referenced by ezbus_mac_arbiter_rst_warmboot_cycles().
void ezbus_mac_arbiter_transmit_init (ezbus_mac_t * mac)
Definition at line 35 of file ezbus_mac_arbiter_transmit.c.
References _ezbus_mac_arbiter_transmit_t::ack_tx_timer, ezbus_mac_get_arbiter_transmit(), ezbus_mac_token_ring_time(), ezbus_timer_init(), ezbus_timer_set_callback(), ezbus_timer_set_key(), and ezbus_timer_set_period().
Referenced by ezbus_mac_init().
void ezbus_mac_arbiter_transmit_reset (ezbus_mac_t * mac)
Definition at line 212 of file ezbus_mac_arbiter_transmit.c.
References _ezbus_mac_arbiter_transmit_t::ack_tx_count, _ezbus_mac_arbiter_transmit_t::ack_tx_timer, ezbus_mac_get_arbiter_transmit(), and ezbus_timer_stop.
Referenced by ezbus_mac_arbiter_receive_run(), and ezbus_mac_transmitter_signal_wait().
void ezbus_mac_arbiter_transmit_run (ezbus_mac_t * mac)
Definition at line 45 of file ezbus_mac_arbiter_transmit.c.
References _ezbus_mac_arbiter_transmit_t::ack_tx_timer, ezbus_mac_get_arbiter_transmit(), and ezbus_timer_run().
Referenced by ezbus_mac_run().
void ezbuz_mac_arbiter_transmit_token (ezbus_mac_t * mac)
Definition at line 231 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), EZBUS_LOG_TOKEN, ezbus_mac_arbiter_get_token_age(), ezbus_mac_peers_crc(), ezbus_mac_peers_log(), ezbus_mac_peers_next(), ezbus_mac_transmitter_put(), ezbus_packet_init(), ezbus_packet_set_dst(), ezbus_packet_set_dst_socket(), ezbus_packet_set_seq(), ezbus_packet_set_src(), ezbus_packet_set_src_socket(), ezbus_packet_set_token_age(), ezbus_packet_set_token_crc(), ezbus_packet_set_type(), ezbus_self_address, EZBUS_SOCKET_ANY, and packet_type_give_token.
Referenced by ezbus_mac_arbiter_rst_warmboot_cycles().