EzBus: src/mac/ezbus_mac_receiver.h File Reference
ezbus_mac_receiver.h File Reference
#include <ezbus_platform.h>
#include <ezbus_mac.h>
#include <ezbus_timer.h>
Classes
struct _ezbus_mac_receiver_t
Typedefs
typedef struct _ezbus_mac_receiver_t ezbus_mac_receiver_t
Enumerations
enum ezbus_receiver_state_t { receiver_state_empty =0, receiver_state_full, receiver_state_receive_fault }
Functions
void ezbus_mac_receiver_init (ezbus_mac_t *mac)
void ezbus_mac_receiver_run (ezbus_mac_t *mac)
void ezbus_mac_receiver_get (ezbus_mac_t *mac, ezbus_packet_t *packet)
void ezbus_mac_receiver_set_err (ezbus_mac_t *mac, EZBUS_ERR err)
EZBUS_ERR ezbus_mac_receiver_get_err (ezbus_mac_t *mac)
void ezbus_mac_receiver_set_state (ezbus_mac_t *mac, ezbus_receiver_state_t state)
ezbus_receiver_state_t ezbus_mac_receiver_get_state (ezbus_mac_t *mac)
void ezbus_mac_receiver_signal_empty (ezbus_mac_t *mac)
void ezbus_mac_receiver_signal_full (ezbus_mac_t *mac)
void ezbus_mac_receiver_signal_fault (ezbus_mac_t *mac)
Typedef Documentation
typedef struct _ezbus_mac_receiver_t ezbus_mac_receiver_t
Enumeration Type Documentation
enum ezbus_receiver_state_t
Enumerator
receiver_state_empty
receiver_state_full
receiver_state_receive_fault
Definition at line 29 of file ezbus_mac_receiver.h.
Function Documentation
void ezbus_mac_receiver_get (ezbus_mac_t * mac, ezbus_packet_t * packet)
Definition at line 83 of file ezbus_mac_receiver.c.
References EZBUS_ERR_OKAY, ezbus_mac_get_port(), ezbus_mac_get_receiver_packet(), ezbus_mac_receiver_get_err(), ezbus_mac_receiver_set_err(), ezbus_mac_receiver_set_state(), ezbus_mac_receiver_signal_empty(), ezbus_mac_receiver_signal_fault(), ezbus_mac_receiver_signal_full(), ezbus_packet_copy(), ezbus_port_recv(), receiver_state_empty, receiver_state_full, and receiver_state_receive_fault.
EZBUS_ERR ezbus_mac_receiver_get_err (ezbus_mac_t * mac)
Definition at line 75 of file ezbus_mac_receiver.c.
References _ezbus_mac_receiver_t::err, and ezbus_mac_get_receiver().
Referenced by ezbus_mac_receiver_get(), and ezbus_mac_receiver_signal_fault().
ezbus_receiver_state_t ezbus_mac_receiver_get_state (ezbus_mac_t * mac)
Definition at line 63 of file ezbus_mac_receiver.c.
References ezbus_mac_get_receiver(), and _ezbus_mac_receiver_t::state.
Referenced by ezbus_mac_receiver_run().
void ezbus_mac_receiver_init (ezbus_mac_t * mac)
Definition at line 51 of file ezbus_mac_receiver.c.
References ezbus_mac_get_receiver(), and ezbus_platform_memset().
Referenced by ezbus_mac_init().
void ezbus_mac_receiver_run (ezbus_mac_t * mac)
Definition at line 32 of file ezbus_mac_receiver.c.
References ezbus_mac_receiver_get_state(), receiver_state_empty, receiver_state_full, and receiver_state_receive_fault.
Referenced by ezbus_mac_run().
void ezbus_mac_receiver_set_err (ezbus_mac_t * mac, EZBUS_ERR err)
Definition at line 69 of file ezbus_mac_receiver.c.
References _ezbus_mac_receiver_t::err, and ezbus_mac_get_receiver().
Referenced by ezbus_mac_receiver_get().
void ezbus_mac_receiver_set_state (ezbus_mac_t * mac, ezbus_receiver_state_t state)
Definition at line 57 of file ezbus_mac_receiver.c.
References ezbus_mac_get_receiver(), and _ezbus_mac_receiver_t::state.
Referenced by ezbus_mac_receiver_get(), and ezbus_mac_receiver_signal_wait().
void ezbus_mac_receiver_signal_empty (ezbus_mac_t * mac)
Definition at line 322 of file ezbus_mac_arbiter_receive.c.
Referenced by ezbus_mac_receiver_get().
void ezbus_mac_receiver_signal_fault (ezbus_mac_t * mac)
Definition at line 340 of file ezbus_mac_arbiter_receive.c.
References EZBUS_ERR_NOTREADY, ezbus_fault_str(), ezbus_log(), EZBUS_LOG_RECEIVER, and ezbus_mac_receiver_get_err().
Referenced by ezbus_mac_receiver_get().
void ezbus_mac_receiver_signal_full (ezbus_mac_t * mac)
Definition at line 295 of file ezbus_mac_arbiter_receive.c.
References ezbus_log(), EZBUS_LOG_RECEIVER, ezbus_mac_coldboot_reset, ezbus_mac_get_receiver_packet(), ezbus_mac_peers_log(), ezbus_packet_type(), packet_type_ack, packet_type_coldboot, packet_type_give_token, packet_type_nack, packet_type_parcel, packet_type_reset, packet_type_speed, packet_type_take_token, packet_type_warmboot_ak, packet_type_warmboot_rp, and packet_type_warmboot_rq.
Referenced by ezbus_mac_receiver_get().