EzBus: src/mac/ezbus_mac_receiver.c File Reference
ezbus_mac_receiver.c File Reference
#include <ezbus_mac_receiver.h>
#include <ezbus_hex.h>
Macros
#define ezbus_mac_receiver_empty(mac_receiver) (ezbus_mac_receiver_get_state((mac_receiver))==receiver_state_empty)
#define ezbus_mac_receiver_full(mac_receiver) (ezbus_mac_receiver_get_state((mac_receiver))!=receiver_state_empty)
Functions
void ezbus_mac_receiver_run (ezbus_mac_t *mac)
void ezbus_mac_receiver_init (ezbus_mac_t *mac)
void ezbus_mac_receiver_set_state (ezbus_mac_t *mac, ezbus_receiver_state_t state)
ezbus_receiver_state_t ezbus_mac_receiver_get_state (ezbus_mac_t *mac)
void ezbus_mac_receiver_set_err (ezbus_mac_t *mac, EZBUS_ERR err)
EZBUS_ERR ezbus_mac_receiver_get_err (ezbus_mac_t *mac)
void ezbus_mac_receiver_get (ezbus_mac_t *mac, ezbus_packet_t *packet)
Macro Definition Documentation
#define ezbus_mac_receiver_empty (mac_receiver) (ezbus_mac_receiver_get_state((mac_receiver))==receiver_state_empty)
Definition at line 25 of file ezbus_mac_receiver.c.
#define ezbus_mac_receiver_full (mac_receiver) (ezbus_mac_receiver_get_state((mac_receiver))!=receiver_state_empty)
Definition at line 26 of file ezbus_mac_receiver.c.
Function Documentation
void ezbus_mac_receiver_get (ezbus_mac_t * mac, ezbus_packet_t * packet)
Definition at line 83 of file ezbus_mac_receiver.c.
References EZBUS_ERR_OKAY, ezbus_mac_get_port(), ezbus_mac_get_receiver_packet(), ezbus_mac_receiver_get_err(), ezbus_mac_receiver_set_err(), ezbus_mac_receiver_set_state(), ezbus_mac_receiver_signal_empty(), ezbus_mac_receiver_signal_fault(), ezbus_mac_receiver_signal_full(), ezbus_packet_copy(), ezbus_port_recv(), receiver_state_empty, receiver_state_full, and receiver_state_receive_fault.
EZBUS_ERR ezbus_mac_receiver_get_err (ezbus_mac_t * mac)
Definition at line 75 of file ezbus_mac_receiver.c.
References _ezbus_mac_receiver_t::err, and ezbus_mac_get_receiver().
Referenced by ezbus_mac_receiver_get(), and ezbus_mac_receiver_signal_fault().
ezbus_receiver_state_t ezbus_mac_receiver_get_state (ezbus_mac_t * mac)
Definition at line 63 of file ezbus_mac_receiver.c.
References ezbus_mac_get_receiver(), and _ezbus_mac_receiver_t::state.
Referenced by ezbus_mac_receiver_run().
void ezbus_mac_receiver_init (ezbus_mac_t * mac)
Definition at line 51 of file ezbus_mac_receiver.c.
References ezbus_mac_get_receiver(), and ezbus_platform_memset().
Referenced by ezbus_mac_init().
void ezbus_mac_receiver_run (ezbus_mac_t * mac)
Definition at line 32 of file ezbus_mac_receiver.c.
References ezbus_mac_receiver_get_state(), receiver_state_empty, receiver_state_full, and receiver_state_receive_fault.
Referenced by ezbus_mac_run().
void ezbus_mac_receiver_set_err (ezbus_mac_t * mac, EZBUS_ERR err)
Definition at line 69 of file ezbus_mac_receiver.c.
References _ezbus_mac_receiver_t::err, and ezbus_mac_get_receiver().
Referenced by ezbus_mac_receiver_get().
void ezbus_mac_receiver_set_state (ezbus_mac_t * mac, ezbus_receiver_state_t state)
Definition at line 57 of file ezbus_mac_receiver.c.
References ezbus_mac_get_receiver(), and _ezbus_mac_receiver_t::state.
Referenced by ezbus_mac_receiver_get(), and ezbus_mac_receiver_signal_wait().