EzBus: src/mac/ezbus_mac_arbiter_receive.h File Reference
ezbus_mac_arbiter_receive.h File Reference
#include <ezbus_mac_arbiter.h>
#include <ezbus_mac.h>
#include <ezbus_timer.h>
#include <ezbus_packet.h>
Classes
struct _ezbus_mac_arbiter_receive_t
Typedefs
typedef struct _ezbus_mac_arbiter_receive_t ezbus_mac_arbiter_receive_t
Functions
void ezbus_mac_arbiter_receive_init (ezbus_mac_t *mac)
void ezbus_mac_arbiter_receive_run (ezbus_mac_t *mac)
void ezbus_mac_arbiter_receive_signal_token (ezbus_mac_t *mac, ezbus_packet_t *packet)
A give-token packet has been received.
void ezbus_mac_arbiter_receive_signal_parcel (ezbus_mac_t *mac, ezbus_packet_t *packet)
Typedef Documentation
typedef struct _ezbus_mac_arbiter_receive_t ezbus_mac_arbiter_receive_t
Function Documentation
void ezbus_mac_arbiter_receive_init (ezbus_mac_t * mac)
Definition at line 54 of file ezbus_mac_arbiter_receive.c.
References _ezbus_mac_arbiter_receive_t::ack_rx_timer, ezbus_mac_get_arbiter_receive(), ezbus_mac_token_ring_time(), ezbus_timer_init(), ezbus_timer_set_callback(), ezbus_timer_set_key(), ezbus_timer_set_period(), and _ezbus_mac_arbiter_receive_t::warmboot_timer.
Referenced by ezbus_mac_init().
void ezbus_mac_arbiter_receive_run (ezbus_mac_t * mac)
Definition at line 69 of file ezbus_mac_arbiter_receive.c.
References _ezbus_mac_arbiter_receive_t::ack_rx_timer, _ezbus_mac_coldboot_t::coldboot_timer, ezbus_address_compare(), ezbus_address_string(), ezbus_broadcast_address, ezbus_log(), EZBUS_LOG_ARBITER, EZBUS_LOG_BOOTSTATE, ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_arbiter_receive_signal_token(), ezbus_mac_arbiter_transmit_reset(), ezbus_mac_coldboot_get_state(), ezbus_mac_coldboot_set_state(), ezbus_mac_get_arbiter_receive(), ezbus_mac_get_coldboot(), ezbus_mac_get_receiver_packet(), ezbus_mac_get_transmitter_packet(), ezbus_mac_peers_insort(), ezbus_mac_peers_log(), ezbus_mac_token_acquired(), ezbus_mac_token_relinquish(), ezbus_mac_transmitter_put(), ezbus_mac_transmitter_set_state(), ezbus_mac_warmboot_set_state(), ezbus_packet_dst(), ezbus_packet_init(), ezbus_packet_seq(), ezbus_packet_set_dst(), ezbus_packet_set_dst_socket(), ezbus_packet_set_seq(), ezbus_packet_set_src(), ezbus_packet_set_src_socket(), ezbus_packet_set_type(), ezbus_packet_src(), ezbus_peer_init(), ezbus_platform_random(), ezbus_self_address, EZBUS_SOCKET_ANY, ezbus_socket_callback_transmitter_ack(), ezbus_socket_callback_transmitter_fault(), ezbus_timer_restart, ezbus_timer_run(), ezbus_timer_set_period(), ezbus_timer_stop, EZBUS_WARMBOOT_TIMER_MAX, EZBUS_WARMBOOT_TIMER_MIN, packet_type_warmboot_ak, packet_type_warmboot_rp, state_coldboot_silent_start, state_coldboot_silent_stop, state_warmboot_idle, transmitter_state_send, _ezbus_mac_arbiter_receive_t::warmboot_seq, and _ezbus_mac_arbiter_receive_t::warmboot_timer.
Referenced by ezbus_mac_run().
void ezbus_mac_arbiter_receive_signal_parcel (ezbus_mac_t * mac, ezbus_packet_t * packet)
BEGIN RECEIVE PARCEL
Definition at line 274 of file ezbus_mac_arbiter.c.
References ezbus_address_compare(), ezbus_address_copy(), ezbus_log(), EZBUS_LOG_RECEIVER, ezbus_mac_get_arbiter(), ezbus_mac_get_receiver_packet(), ezbus_mac_transmitter_put(), ezbus_packet_dst(), ezbus_packet_dst_socket(), ezbus_packet_init(), ezbus_packet_seq(), ezbus_packet_set_dst(), ezbus_packet_set_dst_socket(), ezbus_packet_set_seq(), ezbus_packet_set_src(), ezbus_packet_set_src_socket(), ezbus_packet_set_type(), ezbus_packet_src(), ezbus_packet_src_socket(), ezbus_self_address, ezbus_socket_callback_receiver_ready(), packet_type_ack, _ezbus_mac_arbiter_t::rx_ack_address, _ezbus_mac_arbiter_t::rx_ack_pend, and _ezbus_mac_arbiter_t::rx_ack_seq.
Referenced by ezbus_mac_arbiter_receive_run().
void ezbus_mac_arbiter_receive_signal_token (ezbus_mac_t * mac, ezbus_packet_t * packet)
A give-token packet has been received.
Definition at line 228 of file ezbus_mac_arbiter.c.
References ezbus_address_compare(), ezbus_crc_equal(), ezbus_log(), EZBUS_LOG_TOKEN, ezbus_mac_arbiter_get_state(), ezbus_mac_arbiter_set_state(), ezbus_mac_arbiter_set_token_age(), ezbus_mac_peers_crc(), ezbus_mac_token_acquire(), ezbus_mac_token_reset(), ezbus_packet_dst(), ezbus_packet_get_token_age(), ezbus_packet_get_token_crc(), ezbus_self_address, EZBUS_WARMBOOT_AGE, mac_arbiter_state_online, mac_arbiter_state_reboot_warm, and mac_arbiter_state_service_start.
Referenced by ezbus_mac_arbiter_receive_run().