EzBus: src/socket/ezbus_socket_test1.h File Reference
ezbus_socket_test1.h File Reference
#include <ezbus_platform.h>
#include <ezbus_packet.h>
#include <ezbus_port.h>
#include <ezbus_mac.h>
Functions
void ezbus_port_init (ezbus_port_t *port)
void ezbus_port_run (void)
bool ezbus_port_transmitter_empty (ezbus_mac_t *mac)
bool ezbus_port_transmitter_resend (ezbus_mac_t *mac)
void ezbus_port_transmitter_ack (ezbus_mac_t *mac)
void ezbus_port_transmitter_limit (ezbus_mac_t *mac)
void ezbus_port_transmitter_fault (ezbus_mac_t *mac)
bool ezbus_port_receiver_ready (ezbus_mac_t *mac, ezbus_packet_t *packet)
void ezbus_port_receiver_fault (ezbus_mac_t *mac, ezbus_packet_t *packet)
Function Documentation
void ezbus_port_init (ezbus_port_t * port)
Definition at line 47 of file ezbus_socket_test1.c.
void ezbus_port_receiver_fault (ezbus_mac_t * mac, ezbus_packet_t * packet)
Definition at line 180 of file ezbus_socket_test1.c.
References ezbus_log().
bool ezbus_port_receiver_ready (ezbus_mac_t * mac, ezbus_packet_t * packet)
Definition at line 139 of file ezbus_socket_test1.c.
References ezbus_log(), ezbus_packet_data(), EZBUS_PARCEL_DATA_LN, ezbus_parcel_get_string(), and ezbus_platform_get_ms_ticks().
void ezbus_port_run (void)
Definition at line 53 of file ezbus_socket_test1.c.
void ezbus_port_transmitter_ack (ezbus_mac_t * mac)
Definition at line 117 of file ezbus_socket_test1.c.
References ezbus_log().
bool ezbus_port_transmitter_empty (ezbus_mac_t * mac)
Definition at line 60 of file ezbus_socket_test1.c.
References ezbus_address_compare(), ezbus_broadcast_address, ezbus_log(), ezbus_mac_peers_log(), ezbus_mac_peers_next(), ezbus_mac_transmitter_put(), ezbus_packet_init(), ezbus_packet_set_dst(), ezbus_packet_set_parcel(), ezbus_packet_set_seq(), ezbus_packet_set_src(), ezbus_packet_set_type(), ezbus_parcel_init(), ezbus_parcel_set_string(), ezbus_platform_strcpy(), ezbus_self_address, and packet_type_parcel.
void ezbus_port_transmitter_fault (ezbus_mac_t * mac)
Definition at line 128 of file ezbus_socket_test1.c.
References ezbus_log().
void ezbus_port_transmitter_limit (ezbus_mac_t * mac)
Definition at line 123 of file ezbus_socket_test1.c.
References ezbus_log().
bool ezbus_port_transmitter_resend (ezbus_mac_t * mac)
Definition at line 110 of file ezbus_socket_test1.c.
References ezbus_log(), and ezbus_mac_transmitter_put().