EzBus: src/common/ezbus_string.h File Reference
ezbus_string.h File Reference
#include <ezbus_platform.h>
Classes
struct ezbus_string_t
Macros
#define ezbus_string_append(d, s) ezbus_string_cat((d),(s))
Functions
void ezbus_string_init (ezbus_string_t *string)
void ezbus_string_deinit (ezbus_string_t *string)
char * ezbus_string_str (ezbus_string_t *string)
int ezbus_string_length (ezbus_string_t *string)
void ezbus_string_set_length (ezbus_string_t *string, uint16_t len)
char * ezbus_string_copy (ezbus_string_t *dst, ezbus_string_t *src)
char * ezbus_string_cat (ezbus_string_t *dst, ezbus_string_t *src)
char * ezbus_string_left (ezbus_string_t *dst, ezbus_string_t *src, uint16_t cnt)
char * ezbus_string_right (ezbus_string_t *dst, ezbus_string_t *src, uint16_t cnt)
void ezbus_string_from_c (ezbus_string_t *string, const char *cstr)
void ezbus_string_to_c (ezbus_string_t *string, const char *cstr, uint16_t cstr_max_strlen)
Macro Definition Documentation
#define ezbus_string_append (d, s) ezbus_string_cat((d),(s))
Definition at line 55 of file ezbus_string.h.
Function Documentation
char* ezbus_string_cat (ezbus_string_t * dst, ezbus_string_t * src)
Definition at line 68 of file ezbus_string.c.
References ezbus_string_t::chars, ezbus_platform_realloc(), ezbus_platform_strcat(), ezbus_string_length(), and ezbus_string_str().
char* ezbus_string_copy (ezbus_string_t * dst, ezbus_string_t * src)
Definition at line 61 of file ezbus_string.c.
References ezbus_string_t::chars, ezbus_platform_strcpy(), ezbus_string_length(), ezbus_string_set_length(), and ezbus_string_str().
Referenced by ezbus_string_left(), and ezbus_string_right().
void ezbus_string_deinit (ezbus_string_t * string)
Definition at line 34 of file ezbus_string.c.
References ezbus_string_t::chars.
void ezbus_string_from_c (ezbus_string_t * string, const char * cstr)
Definition at line 96 of file ezbus_string.c.
References ezbus_string_t::chars, ezbus_platform_strlen(), ezbus_platform_strncpy(), and ezbus_string_set_length().
void ezbus_string_init (ezbus_string_t * string)
Definition at line 29 of file ezbus_string.c.
References ezbus_platform_memset().
char* ezbus_string_left (ezbus_string_t * dst, ezbus_string_t * src, uint16_t cnt)
Definition at line 77 of file ezbus_string.c.
References ezbus_string_t::chars, ezbus_platform_strncpy(), ezbus_string_copy(), ezbus_string_length(), ezbus_string_set_length(), and ezbus_string_str().
int ezbus_string_length (ezbus_string_t * string)
Definition at line 46 of file ezbus_string.c.
References ezbus_string_t::chars, and ezbus_platform_strlen().
Referenced by ezbus_string_cat(), ezbus_string_copy(), ezbus_string_left(), and ezbus_string_right().
char* ezbus_string_right (ezbus_string_t * dst, ezbus_string_t * src, uint16_t cnt)
Definition at line 86 of file ezbus_string.c.
References ezbus_string_t::chars, ezbus_platform_strncpy(), ezbus_string_copy(), ezbus_string_length(), ezbus_string_set_length(), and ezbus_string_str().
void ezbus_string_set_length (ezbus_string_t * string, uint16_t len)
Definition at line 54 of file ezbus_string.c.
References ezbus_string_t::chars, ezbus_platform_memset(), and ezbus_platform_realloc().
Referenced by ezbus_string_copy(), ezbus_string_from_c(), ezbus_string_left(), and ezbus_string_right().
char* ezbus_string_str (ezbus_string_t * string)
Definition at line 41 of file ezbus_string.c.
Referenced by ezbus_string_cat(), ezbus_string_copy(), ezbus_string_left(), and ezbus_string_right().
void ezbus_string_to_c (ezbus_string_t * string, const char * cstr, uint16_t cstr_max_strlen)
Definition at line 103 of file ezbus_string.c.
References ezbus_string_t::chars, and ezbus_platform_strncpy().