EzBus: src/mac/ezbus_mac_transmitter.h File Reference
ezbus_mac_transmitter.h File Reference
#include <ezbus_platform.h>
#include <ezbus_mac.h>
Classes
struct _ezbus_mac_transmitter_t
Macros
#define ezbus_mac_transmitter_empty(mac_transmitter) (ezbus_mac_transmitter_get_state((mac_transmitter))==transmitter_state_empty)
#define ezbus_mac_transmitter_full(mac_transmitter) (ezbus_mac_transmitter_get_state((mac_transmitter))!=transmitter_state_empty)
Typedefs
typedef struct _ezbus_mac_transmitter_t ezbus_mac_transmitter_t
Enumerations
enum ezbus_mac_transmitter_state_t { transmitter_state_empty =0, transmitter_state_full, transmitter_state_send, transmitter_state_sent }
Functions
void ezbus_mac_transmitter_init (ezbus_mac_t *mac)
void ezbus_mac_transmitter_run (ezbus_mac_t *mac)
void ezbus_mac_transmitter_flush (ezbus_mac_t *mac)
blocks until transmitter is emptied
void ezbus_mac_transmitter_put (ezbus_mac_t *mac, ezbus_packet_t *packet)
void ezbus_mac_transmitter_reload (ezbus_mac_t *mac)
void ezbus_mac_transmitter_reset (ezbus_mac_t *mac)
void ezbus_mac_transmitter_set_state (ezbus_mac_t *mac, ezbus_mac_transmitter_state_t state)
ezbus_mac_transmitter_state_t ezbus_mac_transmitter_get_state (ezbus_mac_t *mac)
const char * ezbus_mac_transmitter_get_state_str (ezbus_mac_t *mac)
EZBUS_ERR ezbus_mac_transmitter_get_err (ezbus_mac_t *mac)
void ezbus_mac_transmitter_signal_empty (ezbus_mac_t *mac)
void ezbus_mac_transmitter_signal_full (ezbus_mac_t *mac)
void ezbus_mac_transmitter_signal_sent (ezbus_mac_t *mac)
void ezbus_mac_transmitter_signal_wait (ezbus_mac_t *mac)
void ezbus_mac_transmitter_signal_fault (ezbus_mac_t *mac)
Macro Definition Documentation
#define ezbus_mac_transmitter_empty (mac_transmitter) (ezbus_mac_transmitter_get_state((mac_transmitter))==transmitter_state_empty)
Definition at line 66 of file ezbus_mac_transmitter.h.
Referenced by ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_receiver_signal_wait(), ezbus_mac_transmitter_flush(), and ezbus_mac_warmboot_signal_stop().
#define ezbus_mac_transmitter_full (mac_transmitter) (ezbus_mac_transmitter_get_state((mac_transmitter))!=transmitter_state_empty)
Definition at line 67 of file ezbus_mac_transmitter.h.
Typedef Documentation
typedef struct _ezbus_mac_transmitter_t ezbus_mac_transmitter_t
Enumeration Type Documentation
enum ezbus_mac_transmitter_state_t
Enumerator
transmitter_state_empty
transmitter_state_full
transmitter_state_send
transmitter_state_sent
Definition at line 32 of file ezbus_mac_transmitter.h.
Function Documentation
void ezbus_mac_transmitter_flush (ezbus_mac_t * mac)
blocks until transmitter is emptied
Definition at line 73 of file ezbus_mac_transmitter.c.
References ezbus_mac_transmitter_empty, and ezbus_mac_transmitter_run().
EZBUS_ERR ezbus_mac_transmitter_get_err (ezbus_mac_t * mac)
Definition at line 134 of file ezbus_mac_transmitter.c.
References _ezbus_mac_transmitter_t::err, and ezbus_mac_get_transmitter().
Referenced by ezbus_mac_transmitter_reset(), and ezbus_mac_transmitter_signal_fault().
ezbus_mac_transmitter_state_t ezbus_mac_transmitter_get_state (ezbus_mac_t * mac)
Definition at line 147 of file ezbus_mac_transmitter.c.
References ezbus_mac_get_transmitter(), and _ezbus_mac_transmitter_t::state.
Referenced by ezbus_mac_transmitter_get_state_str(), and ezbus_mac_transmitter_run().
const char* ezbus_mac_transmitter_get_state_str (ezbus_mac_t * mac)
Definition at line 153 of file ezbus_mac_transmitter.c.
References ezbus_mac_transmitter_get_state(), transmitter_state_empty, transmitter_state_full, transmitter_state_send, and transmitter_state_sent.
Referenced by ezbus_mac_transmitter_run().
void ezbus_mac_transmitter_init (ezbus_mac_t * mac)
Definition at line 30 of file ezbus_mac_transmitter.c.
References ezbus_mac_get_transmitter(), and ezbus_platform_memset().
Referenced by ezbus_mac_init().
void ezbus_mac_transmitter_put (ezbus_mac_t * mac, ezbus_packet_t * packet)
Definition at line 82 of file ezbus_mac_transmitter.c.
References ezbus_mac_get_transmitter_packet(), ezbus_mac_transmitter_set_state(), ezbus_packet_copy(), and transmitter_state_full.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_warmboot_signal_stop(), ezbus_port_transmitter_empty(), ezbus_port_transmitter_resend(), ezbus_socket_callback_transmitter_resend(), and ezbuz_mac_arbiter_transmit_token().
void ezbus_mac_transmitter_reload (ezbus_mac_t * mac)
Definition at line 89 of file ezbus_mac_transmitter.c.
References ezbus_mac_transmitter_set_state(), and transmitter_state_full.
void ezbus_mac_transmitter_reset (ezbus_mac_t * mac)
Definition at line 94 of file ezbus_mac_transmitter.c.
References _ezbus_mac_transmitter_t::err, EZBUS_ERR_OKAY, ezbus_mac_get_port(), ezbus_mac_get_transmitter(), ezbus_mac_get_transmitter_packet(), ezbus_mac_transmitter_get_err(), ezbus_mac_transmitter_reset(), ezbus_mac_transmitter_set_state(), ezbus_mac_transmitter_signal_fault(), ezbus_mac_transmitter_signal_sent(), ezbus_mac_transmitter_signal_wait(), ezbus_packet_ack_req(), ezbus_packet_type(), ezbus_port_send(), packet_type_parcel, transmitter_state_empty, and transmitter_state_sent.
Referenced by ezbus_mac_transmitter_reset(), and ezbus_mac_transmitter_signal_fault().
void ezbus_mac_transmitter_run (ezbus_mac_t * mac)
Definition at line 38 of file ezbus_mac_transmitter.c.
References ezbus_log(), EZBUS_LOG_TRANSMITTERSTATE, ezbus_mac_transmitter_get_state(), ezbus_mac_transmitter_get_state_str(), ezbus_mac_transmitter_set_state(), ezbus_mac_transmitter_signal_empty(), ezbus_mac_transmitter_signal_full(), transmitter_state_empty, transmitter_state_full, transmitter_state_send, and transmitter_state_sent.
Referenced by ezbus_mac_run(), and ezbus_mac_transmitter_flush().
void ezbus_mac_transmitter_set_state (ezbus_mac_t * mac, ezbus_mac_transmitter_state_t state)
Definition at line 141 of file ezbus_mac_transmitter.c.
References ezbus_mac_get_transmitter(), and _ezbus_mac_transmitter_t::state.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_transmitter_put(), ezbus_mac_transmitter_reload(), ezbus_mac_transmitter_reset(), and ezbus_mac_transmitter_run().
void ezbus_mac_transmitter_signal_empty (ezbus_mac_t * mac)
Definition at line 151 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), and EZBUS_LOG_TRANSMITTER.
Referenced by ezbus_mac_transmitter_run().
void ezbus_mac_transmitter_signal_fault (ezbus_mac_t * mac)
Definition at line 223 of file ezbus_mac_arbiter_transmit.c.
References ezbus_fault_str(), ezbus_log(), EZBUS_LOG_TRANSMITTER, ezbus_mac_transmitter_get_err(), and ezbus_mac_transmitter_reset().
Referenced by ezbus_mac_transmitter_reset().
void ezbus_mac_transmitter_signal_full (ezbus_mac_t * mac)
Definition at line 156 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), and EZBUS_LOG_TRANSMITTER.
Referenced by ezbus_mac_transmitter_run().
void ezbus_mac_transmitter_signal_sent (ezbus_mac_t * mac)
Definition at line 161 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), and EZBUS_LOG_TRANSMITTER.
Referenced by ezbus_mac_transmitter_reset().
void ezbus_mac_transmitter_signal_wait (ezbus_mac_t * mac)
Definition at line 169 of file ezbus_mac_arbiter_transmit.c.
References _ezbus_mac_arbiter_transmit_t::ack_tx_count, _ezbus_mac_arbiter_transmit_t::ack_tx_timer, ezbus_log(), EZBUS_LOG_ARBITER, ezbus_mac_arbiter_transmit_reset(), ezbus_mac_get_arbiter_transmit(), EZBUS_RETRANSMIT_TRIES, ezbus_socket_callback_transmitter_limit(), ezbus_socket_callback_transmitter_resend(), and ezbus_timer_restart.
Referenced by ezbus_mac_transmitter_reset().