EzBus: src/mac/ezbus_mac_arbiter_transmit.c File Reference
ezbus_mac_arbiter_transmit.c File Reference
#include <ezbus_mac_arbiter_transmit.h>
#include <ezbus_mac_transmitter.h>
#include <ezbus_mac_coldboot.h>
#include <ezbus_mac_warmboot.h>
#include <ezbus_mac_token.h>
#include <ezbus_mac_peers.h>
#include <ezbus_socket_callback.h>
#include <ezbus_packet.h>
#include <ezbus_hex.h>
#include <ezbus_log.h>
Functions
void ezbus_mac_arbiter_transmit_init (ezbus_mac_t *mac)
void ezbus_mac_arbiter_transmit_run (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_silent_start (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_silent_continue (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_silent_stop (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_start (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_continue (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_stop (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_dominant (ezbus_mac_t *mac)
Get here once coldboot has determined that we have the dominant address.
void ezbus_mac_warmboot_signal_start (ezbus_mac_t *mac)
void ezbus_mac_warmboot_signal_continue (ezbus_mac_t *mac)
void ezbus_mac_warmboot_signal_stop (ezbus_mac_t *mac)
void ezbus_mac_warmboot_signal_idle (ezbus_mac_t *mac)
void ezbus_mac_transmitter_signal_empty (ezbus_mac_t *mac)
void ezbus_mac_transmitter_signal_full (ezbus_mac_t *mac)
void ezbus_mac_transmitter_signal_sent (ezbus_mac_t *mac)
void ezbus_mac_transmitter_signal_wait (ezbus_mac_t *mac)
bool ezbus_mac_arbiter_transmit_busy (ezbus_mac_t *mac)
void ezbus_mac_arbiter_transmit_reset (ezbus_mac_t *mac)
void ezbus_mac_transmitter_signal_fault (ezbus_mac_t *mac)
void ezbuz_mac_arbiter_transmit_token (ezbus_mac_t *mac)
Function Documentation
bool ezbus_mac_arbiter_transmit_busy (ezbus_mac_t * mac)
Definition at line 205 of file ezbus_mac_arbiter_transmit.c.
References _ezbus_mac_arbiter_transmit_t::ack_tx_count, and ezbus_mac_get_arbiter_transmit().
Referenced by ezbus_mac_arbiter_rst_warmboot_cycles().
void ezbus_mac_arbiter_transmit_init (ezbus_mac_t * mac)
Definition at line 35 of file ezbus_mac_arbiter_transmit.c.
References _ezbus_mac_arbiter_transmit_t::ack_tx_timer, ezbus_mac_get_arbiter_transmit(), ezbus_mac_token_ring_time(), ezbus_timer_init(), ezbus_timer_set_callback(), ezbus_timer_set_key(), and ezbus_timer_set_period().
Referenced by ezbus_mac_init().
void ezbus_mac_arbiter_transmit_reset (ezbus_mac_t * mac)
Definition at line 212 of file ezbus_mac_arbiter_transmit.c.
References _ezbus_mac_arbiter_transmit_t::ack_tx_count, _ezbus_mac_arbiter_transmit_t::ack_tx_timer, ezbus_mac_get_arbiter_transmit(), and ezbus_timer_stop.
Referenced by ezbus_mac_arbiter_receive_run(), and ezbus_mac_transmitter_signal_wait().
void ezbus_mac_arbiter_transmit_run (ezbus_mac_t * mac)
Definition at line 45 of file ezbus_mac_arbiter_transmit.c.
References _ezbus_mac_arbiter_transmit_t::ack_tx_timer, ezbus_mac_get_arbiter_transmit(), and ezbus_timer_run().
Referenced by ezbus_mac_run().
void ezbus_mac_coldboot_signal_continue (ezbus_mac_t * mac)
Definition at line 77 of file ezbus_mac_arbiter_transmit.c.
References ezbus_address_string(), ezbus_log(), EZBUS_LOG_BOOTSTATE, EZBUS_LOG_COLDBOOT, ezbus_mac_coldboot_get_seq(), ezbus_mac_peers_log(), ezbus_mac_token_acquired(), ezbus_mac_transmitter_empty, ezbus_mac_transmitter_put(), ezbus_packet_init(), ezbus_packet_seq(), ezbus_packet_set_dst_socket(), ezbus_packet_set_seq(), ezbus_packet_set_src(), ezbus_packet_set_src_socket(), ezbus_packet_set_type(), ezbus_packet_src(), ezbus_self_address, EZBUS_SOCKET_ANY, and packet_type_coldboot.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_coldboot_signal_dominant (ezbus_mac_t * mac)
Get here once coldboot has determined that we have the dominant address.
Definition at line 107 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), EZBUS_LOG_DOMINANT, ezbus_mac_arbiter_set_state(), ezbus_mac_coldboot_set_state(), ezbus_mac_warmboot_set_state(), mac_arbiter_state_warmboot, state_coldboot_silent_start, and state_warmboot_start.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_coldboot_signal_silent_continue (ezbus_mac_t * mac)
Definition at line 58 of file ezbus_mac_arbiter_transmit.c.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_coldboot_signal_silent_start (ezbus_mac_t * mac)
Definition at line 52 of file ezbus_mac_arbiter_transmit.c.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_coldboot_signal_silent_stop (ezbus_mac_t * mac)
Definition at line 63 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), and EZBUS_LOG_COLDBOOT.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_coldboot_signal_start (ezbus_mac_t * mac)
Definition at line 69 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), EZBUS_LOG_COLDBOOT, ezbus_mac_arbiter_set_state(), ezbus_mac_peers_clear(), ezbus_mac_warmboot_set_state(), mac_arbiter_state_coldboot, and state_warmboot_idle.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_coldboot_signal_stop (ezbus_mac_t * mac)
Definition at line 99 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), and EZBUS_LOG_COLDBOOT.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_transmitter_signal_empty (ezbus_mac_t * mac)
Definition at line 151 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), and EZBUS_LOG_TRANSMITTER.
Referenced by ezbus_mac_transmitter_run().
void ezbus_mac_transmitter_signal_fault (ezbus_mac_t * mac)
Definition at line 223 of file ezbus_mac_arbiter_transmit.c.
References ezbus_fault_str(), ezbus_log(), EZBUS_LOG_TRANSMITTER, ezbus_mac_transmitter_get_err(), and ezbus_mac_transmitter_reset().
Referenced by ezbus_mac_transmitter_reset().
void ezbus_mac_transmitter_signal_full (ezbus_mac_t * mac)
Definition at line 156 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), and EZBUS_LOG_TRANSMITTER.
Referenced by ezbus_mac_transmitter_run().
void ezbus_mac_transmitter_signal_sent (ezbus_mac_t * mac)
Definition at line 161 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), and EZBUS_LOG_TRANSMITTER.
Referenced by ezbus_mac_transmitter_reset().
void ezbus_mac_transmitter_signal_wait (ezbus_mac_t * mac)
Definition at line 169 of file ezbus_mac_arbiter_transmit.c.
References _ezbus_mac_arbiter_transmit_t::ack_tx_count, _ezbus_mac_arbiter_transmit_t::ack_tx_timer, ezbus_log(), EZBUS_LOG_ARBITER, ezbus_mac_arbiter_transmit_reset(), ezbus_mac_get_arbiter_transmit(), EZBUS_RETRANSMIT_TRIES, ezbus_socket_callback_transmitter_limit(), ezbus_socket_callback_transmitter_resend(), and ezbus_timer_restart.
Referenced by ezbus_mac_transmitter_reset().
void ezbus_mac_warmboot_signal_continue (ezbus_mac_t * mac)
Definition at line 121 of file ezbus_mac_arbiter_transmit.c.
Referenced by ezbus_mac_warmboot_get_state().
void ezbus_mac_warmboot_signal_idle (ezbus_mac_t * mac)
Definition at line 146 of file ezbus_mac_arbiter_transmit.c.
Referenced by ezbus_mac_warmboot_get_state().
void ezbus_mac_warmboot_signal_start (ezbus_mac_t * mac)
Definition at line 116 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), and EZBUS_LOG_WARMBOOT.
Referenced by ezbus_mac_warmboot_get_state().
void ezbus_mac_warmboot_signal_stop (ezbus_mac_t * mac)
Definition at line 126 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), EZBUS_LOG_WARMBOOT, ezbus_mac_coldboot_set_state(), ezbus_mac_transmitter_empty, ezbus_mac_transmitter_put(), ezbus_mac_warmboot_get_seq(), ezbus_packet_init(), ezbus_packet_set_dst_socket(), ezbus_packet_set_seq(), ezbus_packet_set_src(), ezbus_packet_set_src_socket(), ezbus_packet_set_type(), ezbus_self_address, EZBUS_SOCKET_ANY, packet_type_warmboot_rq, and state_coldboot_silent_start.
Referenced by ezbus_mac_warmboot_get_state().
void ezbuz_mac_arbiter_transmit_token (ezbus_mac_t * mac)
Definition at line 231 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), EZBUS_LOG_TOKEN, ezbus_mac_arbiter_get_token_age(), ezbus_mac_peers_crc(), ezbus_mac_peers_log(), ezbus_mac_peers_next(), ezbus_mac_transmitter_put(), ezbus_packet_init(), ezbus_packet_set_dst(), ezbus_packet_set_dst_socket(), ezbus_packet_set_seq(), ezbus_packet_set_src(), ezbus_packet_set_src_socket(), ezbus_packet_set_token_age(), ezbus_packet_set_token_crc(), ezbus_packet_set_type(), ezbus_self_address, EZBUS_SOCKET_ANY, and packet_type_give_token.
Referenced by ezbus_mac_arbiter_rst_warmboot_cycles().