EzBus: src/common/ezbus_peer.h File Reference
ezbus_peer.h File Reference
#include <ezbus_platform.h>
Classes
struct ezbus_peer_t
Functions
void ezbus_peer_init (ezbus_peer_t *peer, ezbus_address_t *address, uint8_t seq)
ezbus_address_t * ezbus_peer_get_address (const ezbus_peer_t *peer)
uint8_t ezbus_peer_get_seq (const ezbus_peer_t *peer)
uint8_t ezbus_peer_set_seq (const ezbus_peer_t *peer, uint8_t seq)
int ezbus_peer_compare (const ezbus_peer_t *a, const ezbus_peer_t *b)
Compare address a vs b.
uint8_t * ezbus_peer_copy (ezbus_peer_t *dst, const ezbus_peer_t *src)
void ezbus_peer_swap (ezbus_peer_t *dst, ezbus_peer_t *src)
char * ezbus_peer_string (ezbus_peer_t *peer)
void ezbus_peer_dump (const ezbus_peer_t *peer, const char *prefix)
Function Documentation
int ezbus_peer_compare (const ezbus_peer_t * a, const ezbus_peer_t * b)
Compare address a vs b.
Returns
<, =, or > 0
Definition at line 67 of file ezbus_peer.c.
References ezbus_platform_memcmp().
uint8_t* ezbus_peer_copy (ezbus_peer_t * dst, const ezbus_peer_t * src)
Definition at line 72 of file ezbus_peer.c.
References ezbus_platform_memcpy().
Referenced by ezbus_mac_peers_dump(), and ezbus_peer_swap().
void ezbus_peer_dump (const ezbus_peer_t * peer, const char * prefix)
Definition at line 90 of file ezbus_peer.c.
References ezbus_peer_t::address, ezbus_address_t::byte, EZBUS_ADDR_LN, and ezbus_peer_t::seq.
Referenced by ezbus_mac_peers_dump().
ezbus_address_t* ezbus_peer_get_address (const ezbus_peer_t * peer)
Definition at line 33 of file ezbus_peer.c.
References ezbus_peer_t::address.
Referenced by ezbus_mac_peers_am_dominant(), ezbus_mac_peers_clean(), ezbus_mac_peers_crc(), ezbus_mac_peers_dump(), ezbus_mac_peers_index_of(), ezbus_mac_peers_insort(), ezbus_mac_peers_log(), and ezbus_mac_peers_next().
uint8_t ezbus_peer_get_seq (const ezbus_peer_t * peer)
Definition at line 43 of file ezbus_peer.c.
References ezbus_peer_t::seq.
Referenced by ezbus_mac_peers_clean(), and ezbus_mac_peers_log().
void ezbus_peer_init (ezbus_peer_t * peer, ezbus_address_t * address, uint8_t seq)
Definition at line 27 of file ezbus_peer.c.
References ezbus_peer_t::address, ezbus_address_copy(), and ezbus_peer_t::seq.
Referenced by ezbus_mac_arbiter_receive_run(), and ezbus_mac_peers_clear().
uint8_t ezbus_peer_set_seq (const ezbus_peer_t * peer, uint8_t seq)
Definition at line 52 of file ezbus_peer.c.
References ezbus_peer_t::seq.
Referenced by ezbus_mac_peers_clean().
char* ezbus_peer_string (ezbus_peer_t * peer)
Definition at line 85 of file ezbus_peer.c.
References ezbus_peer_t::address, and ezbus_address_string().
void ezbus_peer_swap (ezbus_peer_t * dst, ezbus_peer_t * src)
Definition at line 77 of file ezbus_peer.c.
References ezbus_peer_copy().