EzBus: src/mac/ezbus_mac_token.c File Reference
ezbus_mac_token.c File Reference
#include <ezbus_mac_token.h>
#include <ezbus_mac_peers.h>
#include <ezbus_log.h>
Macros
#define NUM_PEERS_HACK 1
#define ezbus_mac_token_get_ring_timer(token) (&(token)->ring_timer)
Functions
void ezbus_mac_token_init (ezbus_mac_t *mac)
void ezbus_mac_token_run (ezbus_mac_t *mac)
uint32_t ezbus_mac_token_ring_time (ezbus_mac_t *mac)
uint32_t ezbus_mac_token_retransmit_time (ezbus_mac_t *mac)
void ezbus_mac_token_reset (ezbus_mac_t *mac)
void ezbus_mac_token_acquire (ezbus_mac_t *mac)
void ezbus_mac_token_relinquish (ezbus_mac_t *mac)
bool ezbus_mac_token_acquired (ezbus_mac_t *mac)
Macro Definition Documentation
#define ezbus_mac_token_get_ring_timer (token) (&(token)->ring_timer)
Definition at line 28 of file ezbus_mac_token.c.
Referenced by ezbus_mac_token_acquire(), ezbus_mac_token_acquired(), ezbus_mac_token_init(), ezbus_mac_token_relinquish(), ezbus_mac_token_reset(), and ezbus_mac_token_run().
#define NUM_PEERS_HACK 1
Definition at line 26 of file ezbus_mac_token.c.
Function Documentation
void ezbus_mac_token_acquire (ezbus_mac_t * mac)
Definition at line 75 of file ezbus_mac_token.c.
References _ezbus_mac_token_t::acquired, ezbus_mac_get_token(), ezbus_mac_token_get_ring_timer, ezbus_timer_restart, and _ezbus_mac_t::token.
Referenced by ezbus_mac_arbiter_receive_signal_token(), and ezbus_mac_warmboot_signal_finished().
bool ezbus_mac_token_acquired (ezbus_mac_t * mac)
Definition at line 89 of file ezbus_mac_token.c.
References _ezbus_mac_token_t::acquired, ezbus_mac_get_token(), ezbus_mac_token_get_ring_timer, ezbus_mac_token_signal_expired(), ezbus_timer_restart, and _ezbus_mac_t::token.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_rst_warmboot_cycles(), and ezbus_mac_coldboot_signal_continue().
void ezbus_mac_token_init (ezbus_mac_t * mac)
Definition at line 32 of file ezbus_mac_token.c.
References ezbus_mac_get_token(), ezbus_mac_token_get_ring_timer, ezbus_timer_init(), ezbus_timer_set_callback(), ezbus_timer_set_key(), ezbus_timer_set_period(), and _ezbus_mac_t::token.
Referenced by ezbus_mac_init().
void ezbus_mac_token_relinquish (ezbus_mac_t * mac)
Definition at line 82 of file ezbus_mac_token.c.
References _ezbus_mac_token_t::acquired, ezbus_mac_get_token(), ezbus_mac_token_get_ring_timer, ezbus_timer_restart, and _ezbus_mac_t::token.
Referenced by ezbus_mac_arbiter_receive_run(), and ezbus_mac_arbiter_rst_warmboot_cycles().
void ezbus_mac_token_reset (ezbus_mac_t * mac)
Definition at line 69 of file ezbus_mac_token.c.
References ezbus_mac_get_token(), ezbus_mac_token_get_ring_timer, ezbus_timer_restart, and _ezbus_mac_t::token.
Referenced by ezbus_mac_arbiter_receive_signal_token(), ezbus_mac_arbiter_rst_warmboot_cycles(), and ezbus_mac_warmboot_signal_finished().
uint32_t ezbus_mac_token_retransmit_time (ezbus_mac_t * mac)
Definition at line 64 of file ezbus_mac_token.c.
References ezbus_mac_token_ring_time().
uint32_t ezbus_mac_token_ring_time (ezbus_mac_t * mac)
Definition at line 49 of file ezbus_mac_token.c.
References ezbus_mac_get_port(), ezbus_mac_peers_count(), EZBUS_MAX_PEERS, and ezbus_port_get_speed().
Referenced by ezbus_mac_arbiter_receive_init(), ezbus_mac_arbiter_transmit_init(), ezbus_mac_coldboot_get_state(), ezbus_mac_token_retransmit_time(), and ezbus_mac_token_run().
void ezbus_mac_token_run (ezbus_mac_t * mac)
Definition at line 42 of file ezbus_mac_token.c.
References ezbus_mac_get_token(), ezbus_mac_token_get_ring_timer, ezbus_mac_token_ring_time(), ezbus_timer_run(), ezbus_timer_set_period(), and _ezbus_mac_t::token.
Referenced by ezbus_mac_run().