EzBus: src/mac/ezbus_mac_peers.c File Reference
ezbus_mac_peers.c File Reference
#include <ezbus_platform.h>
#include <ezbus_address.h>
#include <ezbus_mac_peers.h>
#include <ezbus_hex.h>
#include <ezbus_crc.h>
#include <ezbus_log.h>
Functions
void ezbus_mac_peers_init (ezbus_mac_t *mac)
void ezbus_mac_peers_deinit (ezbus_mac_t *mac)
void ezbus_mac_peers_run (ezbus_mac_t *mac)
void ezbus_mac_peers_clear (ezbus_mac_t *mac)
EZBUS_ERR ezbus_mac_peers_insort (ezbus_mac_t *mac, const ezbus_peer_t *peer)
Insert a copy of the peer into the peer list in ascending sorted order, using ezbus_platform_memcmp() as the sort comparator function.
EZBUS_ERR ezbus_mac_peers_take (ezbus_mac_t *mac, int index)
ezbus_peer_t * ezbus_mac_peers_at (ezbus_mac_t *mac, int index)
int ezbus_mac_peers_count (ezbus_mac_t *mac)
int ezbus_mac_peers_empty (ezbus_mac_t *mac)
int ezbus_mac_peers_full (ezbus_mac_t *mac)
int ezbus_mac_peers_index_of (ezbus_mac_t *mac, const ezbus_address_t *address)
ezbus_peer_t * ezbus_mac_peers_lookup (ezbus_mac_t *mac, const ezbus_address_t *address)
ezbus_address_t * ezbus_mac_peers_next (ezbus_mac_t *mac, const ezbus_address_t *address)
locate the peer in the list which follows in sort order from the given address.
void ezbus_mac_peers_dump (ezbus_mac_t *mac, const char *prefix)
void ezbus_mac_peers_clean (ezbus_mac_t *mac, uint8_t seq)
bool ezbus_mac_peers_am_dominant (ezbus_mac_t *mac)
void ezbus_mac_peers_crc (ezbus_mac_t *mac, ezbus_crc_t *crc)
void ezbus_mac_peers_log (ezbus_mac_t *mac)
Function Documentation
bool ezbus_mac_peers_am_dominant (ezbus_mac_t * mac)
Definition at line 261 of file ezbus_mac_peers.c.
References ezbus_address_compare(), ezbus_mac_peers_at(), ezbus_mac_peers_empty(), ezbus_peer_get_address(), and ezbus_self_address.
ezbus_peer_t* ezbus_mac_peers_at (ezbus_mac_t * mac, int index)
Definition at line 115 of file ezbus_mac_peers.c.
References ezbus_mac_get_peers(), ezbus_mac_peers_count(), and _ezbus_mac_peers_t::list.
Referenced by ezbus_mac_peers_am_dominant(), ezbus_mac_peers_clean(), ezbus_mac_peers_crc(), ezbus_mac_peers_dump(), ezbus_mac_peers_index_of(), ezbus_mac_peers_insort(), ezbus_mac_peers_log(), ezbus_mac_peers_lookup(), and ezbus_mac_peers_next().
void ezbus_mac_peers_clean (ezbus_mac_t * mac, uint8_t seq)
Definition at line 242 of file ezbus_mac_peers.c.
References ezbus_address_compare(), ezbus_mac_peers_at(), ezbus_mac_peers_count(), ezbus_mac_peers_take(), ezbus_peer_get_address(), ezbus_peer_get_seq(), ezbus_peer_set_seq(), and ezbus_self_address.
void ezbus_mac_peers_clear (ezbus_mac_t * mac)
Definition at line 50 of file ezbus_mac_peers.c.
References ezbus_log(), EZBUS_LOG_PEERS, ezbus_mac_get_peers(), ezbus_mac_peers_insort(), ezbus_peer_init(), ezbus_platform_memset(), and ezbus_self_address.
Referenced by ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_mac_coldboot_signal_start(), and ezbus_mac_peers_init().
int ezbus_mac_peers_count (ezbus_mac_t * mac)
Definition at line 126 of file ezbus_mac_peers.c.
References _ezbus_mac_peers_t::count, and ezbus_mac_get_peers().
Referenced by ezbus_mac_peers_at(), ezbus_mac_peers_clean(), ezbus_mac_peers_crc(), ezbus_mac_peers_dump(), ezbus_mac_peers_index_of(), ezbus_mac_peers_insort(), ezbus_mac_peers_log(), ezbus_mac_peers_next(), ezbus_mac_peers_take(), and ezbus_mac_token_ring_time().
void ezbus_mac_peers_crc (ezbus_mac_t * mac, ezbus_crc_t * crc)
Definition at line 271 of file ezbus_mac_peers.c.
References ezbus_crc(), ezbus_crc_init(), ezbus_mac_peers_at(), ezbus_mac_peers_count(), and ezbus_peer_get_address().
Referenced by ezbus_mac_arbiter_receive_signal_token(), and ezbuz_mac_arbiter_transmit_token().
void ezbus_mac_peers_deinit (ezbus_mac_t * mac)
Definition at line 39 of file ezbus_mac_peers.c.
References _ezbus_mac_peers_t::count, and ezbus_mac_get_peers().
void ezbus_mac_peers_dump (ezbus_mac_t * mac, const char * prefix)
Definition at line 184 of file ezbus_mac_peers.c.
References _ezbus_mac_peers_t::count, EZBUS_ERR_LIMIT, EZBUS_ERR_OKAY, ezbus_mac_get_peers(), ezbus_mac_peers_at(), ezbus_mac_peers_count(), ezbus_mac_peers_full(), ezbus_mac_peers_index_of(), ezbus_peer_copy(), ezbus_peer_dump(), ezbus_peer_get_address(), ezbus_platform_memmove(), EZBUS_TMP_BUF_SZ, and _ezbus_mac_peers_t::list.
int ezbus_mac_peers_empty (ezbus_mac_t * mac)
Definition at line 132 of file ezbus_mac_peers.c.
References _ezbus_mac_peers_t::count, and ezbus_mac_get_peers().
Referenced by ezbus_mac_peers_am_dominant().
int ezbus_mac_peers_full (ezbus_mac_t * mac)
Definition at line 138 of file ezbus_mac_peers.c.
References _ezbus_mac_peers_t::count, ezbus_mac_get_peers(), and EZBUS_MAX_PEERS.
Referenced by ezbus_mac_peers_dump(), and ezbus_mac_peers_insort().
int ezbus_mac_peers_index_of (ezbus_mac_t * mac, const ezbus_address_t * address)
Definition at line 144 of file ezbus_mac_peers.c.
References ezbus_address_compare(), ezbus_mac_peers_at(), ezbus_mac_peers_count(), and ezbus_peer_get_address().
Referenced by ezbus_mac_peers_dump(), ezbus_mac_peers_insort(), ezbus_mac_peers_lookup(), and ezbus_mac_peers_next().
void ezbus_mac_peers_init (ezbus_mac_t * mac)
Definition at line 34 of file ezbus_mac_peers.c.
References ezbus_mac_peers_clear().
Referenced by ezbus_mac_init().
EZBUS_ERR ezbus_mac_peers_insort (ezbus_mac_t * mac, const ezbus_peer_t * peer)
Insert a copy of the peer into the peer list in ascending sorted order, using ezbus_platform_memcmp() as the sort comparator function.
Parameters
peers A pointer to an initialized list of peers.
peer A pointer to the peer which is to be copied and insorted into the list.
Returns
A pointer to the list copy of the peer or NULL if the operation failed.
Definition at line 65 of file ezbus_mac_peers.c.
References ezbus_address_compare(), ezbus_broadcast_address, EZBUS_ERR_LIMIT, EZBUS_ERR_OKAY, ezbus_mac_peers_at(), ezbus_mac_peers_count(), ezbus_mac_peers_full(), ezbus_mac_peers_index_of(), ezbus_peer_get_address(), and ezbus_warmboot_address.
Referenced by ezbus_mac_arbiter_receive_run(), and ezbus_mac_peers_clear().
void ezbus_mac_peers_log (ezbus_mac_t * mac)
Definition at line 281 of file ezbus_mac_peers.c.
References ezbus_address_string(), ezbus_log(), EZBUS_LOG_PEERS, ezbus_mac_peers_at(), ezbus_mac_peers_count(), ezbus_peer_get_address(), and ezbus_peer_get_seq().
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_receiver_signal_full(), ezbus_port_transmitter_empty(), and ezbuz_mac_arbiter_transmit_token().
ezbus_peer_t* ezbus_mac_peers_lookup (ezbus_mac_t * mac, const ezbus_address_t * address)
Definition at line 157 of file ezbus_mac_peers.c.
References ezbus_mac_peers_at(), and ezbus_mac_peers_index_of().
ezbus_address_t* ezbus_mac_peers_next (ezbus_mac_t * mac, const ezbus_address_t * address)
locate the peer in the list which follows in sort order from the given address.
Returns
A pointer to the next peer, or NULL.
Definition at line 167 of file ezbus_mac_peers.c.
References ezbus_peer_t::address, ezbus_address_compare(), ezbus_mac_peers_at(), ezbus_mac_peers_count(), ezbus_mac_peers_index_of(), and ezbus_peer_get_address().
Referenced by ezbus_port_transmitter_empty(), and ezbuz_mac_arbiter_transmit_token().
void ezbus_mac_peers_run (ezbus_mac_t * mac)
Definition at line 45 of file ezbus_mac_peers.c.
Referenced by ezbus_mac_run().
EZBUS_ERR ezbus_mac_peers_take (ezbus_mac_t * mac, int index)
Definition at line 100 of file ezbus_mac_peers.c.
References _ezbus_mac_peers_t::count, EZBUS_ERR_LIMIT, ezbus_mac_get_peers(), ezbus_mac_peers_count(), ezbus_platform_memmove(), and _ezbus_mac_peers_t::list.
Referenced by ezbus_mac_peers_clean().