EzBus: src/common/ezbus_parcel.h File Reference
ezbus_parcel.h File Reference
#include <ezbus_platform.h>
Classes
struct ezbus_parcel_t
Functions
void ezbus_parcel_init (ezbus_parcel_t *parcel)
uint16_t ezbus_parcel_get_max (ezbus_parcel_t *parcel)
uint16_t ezbus_parcel_get_size (ezbus_parcel_t *parcel)
void * ezbus_parcel_get_ptr (ezbus_parcel_t *parcel)
uint16_t ezbus_parcel_get_data (ezbus_parcel_t *parcel, void *data)
uint16_t ezbus_parcel_get_string (ezbus_parcel_t *parcel, char *string)
uint16_t ezbus_parcel_set_size (ezbus_parcel_t *parcel, uint16_t size)
uint16_t ezbus_parcel_set_data (ezbus_parcel_t *parcel, const void *data, uint16_t size)
uint16_t ezbus_parcel_set_string (ezbus_parcel_t *parcel, const char *string)
void ezbus_parcel_copy (ezbus_parcel_t *dst, ezbus_parcel_t *src)
Function Documentation
void ezbus_parcel_copy (ezbus_parcel_t * dst, ezbus_parcel_t * src)
Definition at line 82 of file ezbus_parcel.c.
References ezbus_platform_memcpy().
uint16_t ezbus_parcel_get_data (ezbus_parcel_t * parcel, void * data)
Definition at line 48 of file ezbus_parcel.c.
References ezbus_parcel_get_ptr(), ezbus_parcel_get_size(), and ezbus_platform_memcpy().
uint16_t ezbus_parcel_get_max (ezbus_parcel_t * parcel)
Definition at line 33 of file ezbus_parcel.c.
References EZBUS_PARCEL_DATA_LN.
Referenced by ezbus_parcel_get_string(), ezbus_parcel_set_data(), and ezbus_parcel_set_string().
void* ezbus_parcel_get_ptr (ezbus_parcel_t * parcel)
Definition at line 43 of file ezbus_parcel.c.
References ezbus_parcel_t::bytes.
Referenced by ezbus_parcel_get_data(), ezbus_parcel_get_string(), ezbus_parcel_set_data(), and ezbus_parcel_set_string().
uint16_t ezbus_parcel_get_size (ezbus_parcel_t * parcel)
Definition at line 38 of file ezbus_parcel.c.
References ezbus_parcel_t::size.
Referenced by ezbus_parcel_get_data(), and ezbus_parcel_set_data().
uint16_t ezbus_parcel_get_string (ezbus_parcel_t * parcel, char * string)
Definition at line 54 of file ezbus_parcel.c.
References ezbus_parcel_get_max(), ezbus_parcel_get_ptr(), ezbus_platform_strlen(), and ezbus_platform_strncpy().
Referenced by ezbus_port_receiver_ready().
void ezbus_parcel_init (ezbus_parcel_t * parcel)
Definition at line 26 of file ezbus_parcel.c.
References ezbus_platform_memset().
Referenced by ezbus_port_transmitter_empty().
uint16_t ezbus_parcel_set_data (ezbus_parcel_t * parcel, const void * data, uint16_t size)
Definition at line 67 of file ezbus_parcel.c.
References ezbus_parcel_get_max(), ezbus_parcel_get_ptr(), ezbus_parcel_get_size(), ezbus_parcel_set_size(), and ezbus_platform_memcpy().
uint16_t ezbus_parcel_set_size (ezbus_parcel_t * parcel, uint16_t size)
Definition at line 62 of file ezbus_parcel.c.
References ezbus_parcel_t::size.
Referenced by ezbus_parcel_set_data(), and ezbus_parcel_set_string().
uint16_t ezbus_parcel_set_string (ezbus_parcel_t * parcel, const char * string)
Definition at line 74 of file ezbus_parcel.c.
References ezbus_parcel_get_max(), ezbus_parcel_get_ptr(), ezbus_parcel_set_size(), ezbus_platform_strlen(), and ezbus_platform_strncpy().
Referenced by ezbus_port_transmitter_empty().