EzBus: src/mac/ezbus_mac_coldboot.h File Reference
ezbus_mac_coldboot.h File Reference
#include <ezbus_platform.h>
#include <ezbus_timer.h>
#include <ezbus_packet.h>
#include <ezbus_port.h>
#include <ezbus_mac.h>
Classes
struct _ezbus_mac_coldboot_t
Macros
#define ezbus_mac_coldboot_reset(mac) ezbus_mac_coldboot_set_state(mac,state_coldboot_silent_start);
Typedefs
typedef struct _ezbus_mac_coldboot_t ezbus_mac_coldboot_t
Enumerations
enum ezbus_mac_coldboot_state_t {
state_coldboot_silent_start =0, state_coldboot_silent_continue, state_coldboot_silent_stop, state_coldboot_start,
state_coldboot_continue, state_coldboot_stop, state_coldboot_dominant
}
Functions
void ezbus_mac_coldboot_init (ezbus_mac_t *mac)
void ezbus_mac_coldboot_run (ezbus_mac_t *mac)
uint8_t ezbus_mac_coldboot_get_seq (ezbus_mac_t *mac)
void ezbus_mac_coldboot_set_state (ezbus_mac_t *mac, ezbus_mac_coldboot_state_t state)
ezbus_mac_coldboot_state_t ezbus_mac_coldboot_get_state (ezbus_mac_t *mac)
const char * ezbus_mac_coldboot_get_state_str (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_silent_start (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_silent_continue (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_silent_stop (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_start (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_continue (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_stop (ezbus_mac_t *mac)
void ezbus_mac_coldboot_signal_dominant (ezbus_mac_t *mac)
Get here once coldboot has determined that we have the dominant address.
Macro Definition Documentation
#define ezbus_mac_coldboot_reset (mac) ezbus_mac_coldboot_set_state(mac,state_coldboot_silent_start);
Definition at line 83 of file ezbus_mac_coldboot.h.
Referenced by ezbus_mac_arbiter_rst_warmboot_cycles(), and ezbus_mac_receiver_signal_full().
Typedef Documentation
typedef struct _ezbus_mac_coldboot_t ezbus_mac_coldboot_t
Enumeration Type Documentation
enum ezbus_mac_coldboot_state_t
Enumerator
state_coldboot_silent_start
state_coldboot_silent_continue
state_coldboot_silent_stop
state_coldboot_start
state_coldboot_continue
state_coldboot_stop
state_coldboot_dominant
Definition at line 31 of file ezbus_mac_coldboot.h.
Function Documentation
uint8_t ezbus_mac_coldboot_get_seq (ezbus_mac_t * mac)
Definition at line 87 of file ezbus_mac_coldboot.c.
References ezbus_mac_get_coldboot(), and _ezbus_mac_coldboot_t::seq.
Referenced by ezbus_mac_coldboot_signal_continue().
ezbus_mac_coldboot_state_t ezbus_mac_coldboot_get_state (ezbus_mac_t * mac)
Definition at line 120 of file ezbus_mac_coldboot.c.
References _ezbus_mac_coldboot_t::coldboot_timer, EZBUS_COLDBOOT_CYCLES, EZBUS_COLDBOOT_SILENT_TIME, EZBUS_COLDBOOT_TIMER_MAX, EZBUS_COLDBOOT_TIMER_MIN, ezbus_mac_coldboot_get_emit_count, ezbus_mac_coldboot_inc_emit_count, ezbus_mac_coldboot_set_emit_count, ezbus_mac_coldboot_set_state(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_coldboot_signal_dominant(), ezbus_mac_coldboot_signal_silent_continue(), ezbus_mac_coldboot_signal_silent_start(), ezbus_mac_coldboot_signal_silent_stop(), ezbus_mac_coldboot_signal_start(), ezbus_mac_coldboot_signal_stop(), ezbus_mac_get_coldboot(), ezbus_mac_token_ring_time(), ezbus_platform_random(), ezbus_timer_expired, ezbus_timer_set_period(), ezbus_timer_start, ezbus_timer_stop, _ezbus_mac_coldboot_t::seq, _ezbus_mac_coldboot_t::silent_timer, _ezbus_mac_coldboot_t::state, state_coldboot_continue, state_coldboot_dominant, state_coldboot_silent_continue, state_coldboot_silent_start, state_coldboot_silent_stop, and state_coldboot_start.
Referenced by ezbus_mac_arbiter_receive_run(), and ezbus_mac_coldboot_run().
const char* ezbus_mac_coldboot_get_state_str (ezbus_mac_t * mac)
Definition at line 93 of file ezbus_mac_coldboot.c.
References ezbus_mac_get_coldboot(), _ezbus_mac_coldboot_t::state, state_coldboot_continue, state_coldboot_dominant, state_coldboot_silent_continue, state_coldboot_silent_start, state_coldboot_silent_stop, state_coldboot_start, and state_coldboot_stop.
void ezbus_mac_coldboot_init (ezbus_mac_t * mac)
Definition at line 50 of file ezbus_mac_coldboot.c.
References _ezbus_mac_coldboot_t::coldboot_timer, ezbus_mac_get_coldboot(), ezbus_platform_memset(), ezbus_timer_init(), ezbus_timer_set_callback(), ezbus_timer_set_key(), and _ezbus_mac_coldboot_t::silent_timer.
Referenced by ezbus_mac_init().
void ezbus_mac_coldboot_run (ezbus_mac_t * mac)
Definition at line 66 of file ezbus_mac_coldboot.c.
References _ezbus_mac_coldboot_t::coldboot_timer, ezbus_mac_coldboot_get_state(), ezbus_mac_get_coldboot(), ezbus_timer_run(), _ezbus_mac_coldboot_t::silent_timer, state_coldboot_continue, state_coldboot_dominant, state_coldboot_silent_continue, state_coldboot_silent_start, state_coldboot_silent_stop, state_coldboot_start, and state_coldboot_stop.
Referenced by ezbus_mac_run().
void ezbus_mac_coldboot_set_state (ezbus_mac_t * mac, ezbus_mac_coldboot_state_t state)
Definition at line 113 of file ezbus_mac_coldboot.c.
References ezbus_mac_get_coldboot(), and _ezbus_mac_coldboot_t::state.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_mac_coldboot_get_state(), ezbus_mac_coldboot_signal_dominant(), and ezbus_mac_warmboot_signal_stop().
void ezbus_mac_coldboot_signal_continue (ezbus_mac_t * mac)
Definition at line 77 of file ezbus_mac_arbiter_transmit.c.
References ezbus_address_string(), ezbus_log(), EZBUS_LOG_BOOTSTATE, EZBUS_LOG_COLDBOOT, ezbus_mac_coldboot_get_seq(), ezbus_mac_peers_log(), ezbus_mac_token_acquired(), ezbus_mac_transmitter_empty, ezbus_mac_transmitter_put(), ezbus_packet_init(), ezbus_packet_seq(), ezbus_packet_set_dst_socket(), ezbus_packet_set_seq(), ezbus_packet_set_src(), ezbus_packet_set_src_socket(), ezbus_packet_set_type(), ezbus_packet_src(), ezbus_self_address, EZBUS_SOCKET_ANY, and packet_type_coldboot.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_coldboot_signal_dominant (ezbus_mac_t * mac)
Get here once coldboot has determined that we have the dominant address.
Definition at line 107 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), EZBUS_LOG_DOMINANT, ezbus_mac_arbiter_set_state(), ezbus_mac_coldboot_set_state(), ezbus_mac_warmboot_set_state(), mac_arbiter_state_warmboot, state_coldboot_silent_start, and state_warmboot_start.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_coldboot_signal_silent_continue (ezbus_mac_t * mac)
Definition at line 58 of file ezbus_mac_arbiter_transmit.c.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_coldboot_signal_silent_start (ezbus_mac_t * mac)
Definition at line 52 of file ezbus_mac_arbiter_transmit.c.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_coldboot_signal_silent_stop (ezbus_mac_t * mac)
Definition at line 63 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), and EZBUS_LOG_COLDBOOT.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_coldboot_signal_start (ezbus_mac_t * mac)
Definition at line 69 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), EZBUS_LOG_COLDBOOT, ezbus_mac_arbiter_set_state(), ezbus_mac_peers_clear(), ezbus_mac_warmboot_set_state(), mac_arbiter_state_coldboot, and state_warmboot_idle.
Referenced by ezbus_mac_coldboot_get_state().
void ezbus_mac_coldboot_signal_stop (ezbus_mac_t * mac)
Definition at line 99 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), and EZBUS_LOG_COLDBOOT.
Referenced by ezbus_mac_coldboot_get_state().