EzBus: src/common/ezbus_crc.h File Reference
ezbus_crc.h File Reference
#include <ezbus_platform.h>
Classes
union ezbus_crc_t
Functions
void ezbus_crc_init (ezbus_crc_t *crc)
ezbus_crc_t * ezbus_crc (ezbus_crc_t *crc, void *p, size_t size)
ezbus_crc_t * ezbus_crc_update (ezbus_crc_t *crc, uint8_t c)
uint16_t ezbus_crc_word (ezbus_crc_t *crc)
uint8_t * ezbus_crc_bytes (ezbus_crc_t *crc)
bool ezbus_crc_equal (ezbus_crc_t *crc1, ezbus_crc_t *crc2)
ezbus_crc_t * ezbus_crc_flip (ezbus_crc_t *crc)
void ezbus_crc_dump (ezbus_crc_t *crc, const char *prefix)
Function Documentation
ezbus_crc_t* ezbus_crc (ezbus_crc_t * crc, void * p, size_t size)
Definition at line 50 of file ezbus_crc.c.
References ezbus_crc_update().
Referenced by ezbus_mac_peers_crc(), ezbus_packet_calc_crc(), ezbus_packet_data_valid_crc(), and ezbus_packet_header_valid_crc().
uint8_t* ezbus_crc_bytes (ezbus_crc_t * crc)
Definition at line 93 of file ezbus_crc.c.
References ezbus_crc_t::bytes.
void ezbus_crc_dump (ezbus_crc_t * crc, const char * prefix)
Definition at line 69 of file ezbus_crc.c.
References ezbus_crc_t::word.
Referenced by ezbus_packet_dump().
bool ezbus_crc_equal (ezbus_crc_t * crc1, ezbus_crc_t * crc2)
Definition at line 80 of file ezbus_crc.c.
References ezbus_crc_t::word.
Referenced by ezbus_mac_arbiter_receive_signal_token(), ezbus_packet_data_valid_crc(), and ezbus_packet_header_valid_crc().
ezbus_crc_t* ezbus_crc_flip (ezbus_crc_t * crc)
Definition at line 85 of file ezbus_crc.c.
References ezbus_crc_t::bytes.
Referenced by ezbus_packet_data_flip(), and ezbus_packet_header_flip().
void ezbus_crc_init (ezbus_crc_t * crc)
Definition at line 45 of file ezbus_crc.c.
References ezbus_crc_t::word.
Referenced by ezbus_mac_peers_crc(), ezbus_packet_calc_crc(), ezbus_packet_data_valid_crc(), and ezbus_packet_header_valid_crc().
ezbus_crc_t* ezbus_crc_update (ezbus_crc_t * crc, uint8_t c)
Definition at line 60 of file ezbus_crc.c.
References ezbus_crc_t::word.
Referenced by ezbus_crc().
uint16_t ezbus_crc_word (ezbus_crc_t * crc)
Definition at line 75 of file ezbus_crc.c.
References ezbus_crc_t::word.