EzBus: src/mac/ezbus_mac.h File Reference
ezbus_mac.h File Reference
#include <ezbus_platform.h>
#include <ezbus_port.h>
Typedefs
typedef struct _ezbus_mac_t ezbus_mac_t
typedef struct _ezbus_mac_peers_t ezbus_mac_peers_t
typedef struct _ezbus_mac_coldboot_t ezbus_mac_coldboot_t
typedef struct _ezbus_mac_warmboot_t ezbus_mac_warmboot_t
typedef struct _ezbus_mac_transmitter_t ezbus_mac_transmitter_t
typedef struct _ezbus_mac_receiver_t ezbus_mac_receiver_t
typedef struct _ezbus_mac_arbiter_t ezbus_mac_arbiter_t
typedef struct _ezbus_mac_arbiter_receive_t ezbus_mac_arbiter_receive_t
typedef struct _ezbus_mac_arbiter_transmit_t ezbus_mac_arbiter_transmit_t
typedef struct _ezbus_mac_token_t ezbus_mac_token_t
Functions
void ezbus_mac_init (ezbus_mac_t *mac, ezbus_port_t *port)
void ezbus_mac_run (ezbus_mac_t *mac)
ezbus_port_t * ezbus_mac_get_port (ezbus_mac_t *mac)
ezbus_mac_peers_t * ezbus_mac_get_peers (ezbus_mac_t *mac)
ezbus_mac_coldboot_t * ezbus_mac_get_coldboot (ezbus_mac_t *mac)
ezbus_mac_warmboot_t * ezbus_mac_get_warmboot (ezbus_mac_t *mac)
ezbus_mac_transmitter_t * ezbus_mac_get_transmitter (ezbus_mac_t *mac)
ezbus_mac_receiver_t * ezbus_mac_get_receiver (ezbus_mac_t *mac)
ezbus_mac_arbiter_t * ezbus_mac_get_arbiter (ezbus_mac_t *mac)
ezbus_mac_arbiter_receive_t * ezbus_mac_get_arbiter_receive (ezbus_mac_t *mac)
ezbus_mac_arbiter_transmit_t * ezbus_mac_get_arbiter_transmit (ezbus_mac_t *mac)
ezbus_mac_token_t * ezbus_mac_get_token (ezbus_mac_t *mac)
ezbus_packet_t * ezbus_mac_get_transmitter_packet (ezbus_mac_t *mac)
ezbus_packet_t * ezbus_mac_get_receiver_packet (ezbus_mac_t *mac)
Typedef Documentation
typedef struct _ezbus_mac_arbiter_receive_t ezbus_mac_arbiter_receive_t
Definition at line 35 of file ezbus_mac.h.
typedef struct _ezbus_mac_arbiter_t ezbus_mac_arbiter_t
Definition at line 34 of file ezbus_mac.h.
typedef struct _ezbus_mac_arbiter_transmit_t ezbus_mac_arbiter_transmit_t
Definition at line 36 of file ezbus_mac.h.
typedef struct _ezbus_mac_coldboot_t ezbus_mac_coldboot_t
Definition at line 30 of file ezbus_mac.h.
typedef struct _ezbus_mac_peers_t ezbus_mac_peers_t
Definition at line 29 of file ezbus_mac.h.
typedef struct _ezbus_mac_receiver_t ezbus_mac_receiver_t
Definition at line 33 of file ezbus_mac.h.
typedef struct _ezbus_mac_t ezbus_mac_t
Definition at line 28 of file ezbus_mac.h.
typedef struct _ezbus_mac_token_t ezbus_mac_token_t
Definition at line 37 of file ezbus_mac.h.
typedef struct _ezbus_mac_transmitter_t ezbus_mac_transmitter_t
Definition at line 32 of file ezbus_mac.h.
typedef struct _ezbus_mac_warmboot_t ezbus_mac_warmboot_t
Definition at line 31 of file ezbus_mac.h.
Function Documentation
ezbus_mac_arbiter_t* ezbus_mac_get_arbiter (ezbus_mac_t * mac)
Definition at line 86 of file ezbus_mac.c.
References _ezbus_mac_t::arbiter.
Referenced by ezbus_mac_arbiter_dec_warmboot_cycles(), ezbus_mac_arbiter_get_state(), ezbus_mac_arbiter_get_token_age(), ezbus_mac_arbiter_get_warmboot_cycles(), ezbus_mac_arbiter_init(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_mac_arbiter_set_state(), ezbus_mac_arbiter_set_token_age(), and ezbus_mac_arbiter_set_warmboot_cycles().
ezbus_mac_arbiter_receive_t* ezbus_mac_get_arbiter_receive (ezbus_mac_t * mac)
Definition at line 91 of file ezbus_mac.c.
References _ezbus_mac_t::arbiter_receive.
Referenced by ezbus_mac_arbiter_receive_init(), and ezbus_mac_arbiter_receive_run().
ezbus_mac_arbiter_transmit_t* ezbus_mac_get_arbiter_transmit (ezbus_mac_t * mac)
Definition at line 96 of file ezbus_mac.c.
References _ezbus_mac_t::arbiter_transmit.
Referenced by ezbus_mac_arbiter_transmit_busy(), ezbus_mac_arbiter_transmit_init(), ezbus_mac_arbiter_transmit_reset(), ezbus_mac_arbiter_transmit_run(), and ezbus_mac_transmitter_signal_wait().
ezbus_mac_coldboot_t* ezbus_mac_get_coldboot (ezbus_mac_t * mac)
Definition at line 66 of file ezbus_mac.c.
References _ezbus_mac_t::coldboot.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_coldboot_get_seq(), ezbus_mac_coldboot_get_state(), ezbus_mac_coldboot_get_state_str(), ezbus_mac_coldboot_init(), ezbus_mac_coldboot_run(), and ezbus_mac_coldboot_set_state().
ezbus_mac_peers_t* ezbus_mac_get_peers (ezbus_mac_t * mac)
Definition at line 61 of file ezbus_mac.c.
References _ezbus_mac_t::peers.
Referenced by ezbus_mac_peers_at(), ezbus_mac_peers_clear(), ezbus_mac_peers_count(), ezbus_mac_peers_deinit(), ezbus_mac_peers_dump(), ezbus_mac_peers_empty(), ezbus_mac_peers_full(), and ezbus_mac_peers_take().
ezbus_port_t* ezbus_mac_get_port (ezbus_mac_t * mac)
Definition at line 56 of file ezbus_mac.c.
References _ezbus_mac_t::port.
Referenced by ezbus_mac_receiver_get(), ezbus_mac_token_ring_time(), and ezbus_mac_transmitter_reset().
ezbus_mac_receiver_t* ezbus_mac_get_receiver (ezbus_mac_t * mac)
Definition at line 81 of file ezbus_mac.c.
References _ezbus_mac_t::receiver.
Referenced by ezbus_mac_receiver_get_err(), ezbus_mac_receiver_get_state(), ezbus_mac_receiver_init(), ezbus_mac_receiver_set_err(), and ezbus_mac_receiver_set_state().
ezbus_packet_t* ezbus_mac_get_receiver_packet (ezbus_mac_t * mac)
Definition at line 111 of file ezbus_mac.c.
References _ezbus_mac_receiver_t::packet, and _ezbus_mac_t::receiver.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_receiver_get(), ezbus_mac_receiver_signal_full(), ezbus_socket_callback_receiver_ready(), ezbus_socket_callback_transmitter_ack(), ezbus_socket_callback_transmitter_resend(), and ezbus_socket_rx_packet().
ezbus_mac_token_t* ezbus_mac_get_token (ezbus_mac_t * mac)
Definition at line 101 of file ezbus_mac.c.
References _ezbus_mac_t::token.
Referenced by ezbus_mac_token_acquire(), ezbus_mac_token_acquired(), ezbus_mac_token_init(), ezbus_mac_token_relinquish(), ezbus_mac_token_reset(), and ezbus_mac_token_run().
ezbus_mac_transmitter_t* ezbus_mac_get_transmitter (ezbus_mac_t * mac)
Definition at line 76 of file ezbus_mac.c.
References _ezbus_mac_t::transmitter.
Referenced by ezbus_mac_transmitter_get_err(), ezbus_mac_transmitter_get_state(), ezbus_mac_transmitter_init(), ezbus_mac_transmitter_reset(), and ezbus_mac_transmitter_set_state().
ezbus_packet_t* ezbus_mac_get_transmitter_packet (ezbus_mac_t * mac)
Definition at line 106 of file ezbus_mac.c.
References _ezbus_mac_transmitter_t::packet, and _ezbus_mac_t::transmitter.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_transmitter_put(), and ezbus_mac_transmitter_reset().
ezbus_mac_warmboot_t* ezbus_mac_get_warmboot (ezbus_mac_t * mac)
Definition at line 71 of file ezbus_mac.c.
References _ezbus_mac_t::warmboot.
Referenced by ezbus_mac_warmboot_get_seq(), ezbus_mac_warmboot_get_state(), ezbus_mac_warmboot_get_state_str(), ezbus_mac_warmboot_init(), ezbus_mac_warmboot_run(), and ezbus_mac_warmboot_set_state().
void ezbus_mac_init (ezbus_mac_t * mac, ezbus_port_t * port)
Definition at line 25 of file ezbus_mac.c.
References ezbus_address_init(), ezbus_mac_arbiter_init(), ezbus_mac_arbiter_receive_init(), ezbus_mac_arbiter_transmit_init(), ezbus_mac_coldboot_init(), ezbus_mac_peers_init(), ezbus_mac_receiver_init(), ezbus_mac_token_init(), ezbus_mac_transmitter_init(), ezbus_mac_warmboot_init(), and _ezbus_mac_t::port.
Referenced by ezbus_init().
void ezbus_mac_run (ezbus_mac_t * mac)
Definition at line 44 of file ezbus_mac.c.
References ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_run(), ezbus_mac_arbiter_transmit_run(), ezbus_mac_coldboot_run(), ezbus_mac_peers_run(), ezbus_mac_receiver_run(), ezbus_mac_token_run(), ezbus_mac_transmitter_run(), and ezbus_mac_warmboot_run().
Referenced by ezbus_run().