EzBus: src/socket/ezbus_socket_common.h File Reference
ezbus_socket_common.h File Reference
#include <ezbus_platform.h>
#include <ezbus_packet.h>
#include <ezbus_mac.h>
#include <ezbus_fault.h>
Classes
struct _ezbus_socket_state_t
Typedefs
typedef struct _ezbus_socket_state_t ezbus_socket_state_t
Functions
ezbus_mac_t * ezbus_socket_mac (ezbus_socket_t socket)
ezbus_packet_t * ezbus_socket_tx_packet (ezbus_socket_t socket)
uint8_t ezbus_socket_tx_seq (ezbus_socket_t socket)
void ezbus_socket_set_tx_seq (ezbus_socket_t socket, uint8_t seq)
ezbus_packet_t * ezbus_socket_rx_packet (ezbus_socket_t socket)
uint8_t ezbus_socket_rx_seq (ezbus_socket_t socket)
void ezbus_socket_set_rx_seq (ezbus_socket_t socket, uint8_t seq)
EZBUS_ERR ezbus_socket_err (ezbus_socket_t socket)
void ezbus_socket_reset_err (ezbus_socket_t socket)
size_t ezbus_socket_max (void)
ezbus_socket_state_t * ezbus_socket_at (size_t index)
Variables
ezbus_socket_state_t ezbus_sockets []
Typedef Documentation
typedef struct _ezbus_socket_state_t ezbus_socket_state_t
Function Documentation
ezbus_socket_state_t* ezbus_socket_at (size_t index)
Definition at line 32 of file ezbus_socket_common.c.
References ezbus_socket_max(), and ezbus_sockets.
Referenced by ezbus_socket_err(), ezbus_socket_mac(), ezbus_socket_reset_err(), ezbus_socket_rx_seq(), ezbus_socket_set_rx_seq(), ezbus_socket_set_tx_seq(), ezbus_socket_tx_packet(), and ezbus_socket_tx_seq().
EZBUS_ERR ezbus_socket_err (ezbus_socket_t socket)
Definition at line 120 of file ezbus_socket_common.c.
References _ezbus_socket_state_t::err, EZBUS_ERR_OKAY, EZBUS_ERR_RANGE, ezbus_socket_at(), and ezbus_socket_max().
ezbus_mac_t* ezbus_socket_mac (ezbus_socket_t socket)
Definition at line 41 of file ezbus_socket_common.c.
References EZBUS_ERR_RANGE, ezbus_socket_at(), ezbus_socket_max(), and _ezbus_socket_state_t::mac.
Referenced by ezbus_socket_callback_transmitter_ack(), ezbus_socket_is_open(), ezbus_socket_recv(), and ezbus_socket_rx_packet().
size_t ezbus_socket_max (void)
Definition at line 27 of file ezbus_socket_common.c.
References EZBUS_MAX_SOCKETS.
Referenced by ezbus_socket_at(), ezbus_socket_callback_transmitter_empty(), ezbus_socket_err(), ezbus_socket_init(), ezbus_socket_mac(), ezbus_socket_recv(), and ezbus_socket_reset_err().
void ezbus_socket_reset_err (ezbus_socket_t socket)
Definition at line 137 of file ezbus_socket_common.c.
References _ezbus_socket_state_t::err, EZBUS_ERR_OKAY, EZBUS_ERR_RANGE, ezbus_socket_at(), and ezbus_socket_max().
ezbus_packet_t* ezbus_socket_rx_packet (ezbus_socket_t socket)
Definition at line 66 of file ezbus_socket_common.c.
References EZBUS_ERR_NOTREADY, ezbus_mac_get_receiver_packet(), ezbus_socket_is_open(), and ezbus_socket_mac().
uint8_t ezbus_socket_rx_seq (ezbus_socket_t socket)
Definition at line 88 of file ezbus_socket_common.c.
References EZBUS_ERR_NOTREADY, ezbus_socket_at(), ezbus_socket_is_open(), and _ezbus_socket_state_t::rx_seq.
void ezbus_socket_set_rx_seq (ezbus_socket_t socket, uint8_t seq)
Definition at line 109 of file ezbus_socket_common.c.
References EZBUS_ERR_NOTREADY, ezbus_socket_at(), ezbus_socket_is_open(), and _ezbus_socket_state_t::rx_seq.
void ezbus_socket_set_tx_seq (ezbus_socket_t socket, uint8_t seq)
Definition at line 99 of file ezbus_socket_common.c.
References EZBUS_ERR_NOTREADY, ezbus_socket_at(), ezbus_socket_is_open(), and _ezbus_socket_state_t::tx_seq.
Referenced by ezbus_socket_callback_transmitter_ack().
ezbus_packet_t* ezbus_socket_tx_packet (ezbus_socket_t socket)
Definition at line 55 of file ezbus_socket_common.c.
References EZBUS_ERR_RANGE, ezbus_socket_at(), and _ezbus_socket_state_t::tx_packet.
Referenced by ezbus_socket_callback_transmitter_resend().
uint8_t ezbus_socket_tx_seq (ezbus_socket_t socket)
Definition at line 77 of file ezbus_socket_common.c.
References EZBUS_ERR_NOTREADY, ezbus_socket_at(), ezbus_socket_is_open(), and _ezbus_socket_state_t::tx_seq.
Referenced by ezbus_socket_callback_transmitter_ack().
Variable Documentation
ezbus_socket_state_t ezbus_sockets[]
Definition at line 33 of file ezbus_socket.c.
Referenced by ezbus_socket_at().