EzBus: src/common/ezbus_packet.h File Reference
ezbus_packet.h File Reference
#include <ezbus_platform.h>
#include <ezbus_parcel.h>
#include <ezbus_address.h>
#include <ezbus_crc.h>
Classes
struct ezbus_header_t
union ezbus_speed_t
struct ezbus_token_t
struct ezbus_data_t
struct ezbus_packet_t
Macros
#define PACKET_BITS_VERSION_POS 0
#define PACKET_BITS_VERSION_MASK (0x0F<<PACKET_BITS_VERSION_POS)
#define PACKET_BITS_VERSION_0 (0x01<<PACKET_BITS_VERSION_POS)
#define PACKET_BITS_VERSION_1 (0x02<<PACKET_BITS_VERSION_POS)
#define PACKET_BITS_VERSION_2 (0x04<<PACKET_BITS_VERSION_POS)
#define PACKET_BITS_VERSION_3 (0x08<<PACKET_BITS_VERSION_POS)
#define PACKET_BITS_VERSION (PACKET_BITS_VERSION_0)
#define PACKET_BITS_CHAIN_POS 4
#define PACKET_BITS_CHAIN_MASK (0x03<<PACKET_BITS_CHAIN_POS)
#define PACKET_BITS_CHAIN_0 (0x01<<PACKET_BITS_CHAIN_POS)
#define PACKET_BITS_CHAIN_1 (0x02<<PACKET_BITS_CHAIN_POS)
#define PACKET_BITS_CHAIN_BEGIN (PACKET_BITS_CHAIN_0)
#define PACKET_BITS_CHAIN_MIDDLE (0x00)
#define PACKET_BITS_CHAIN_LAST (PACKET_BITS_CHAIN_1)
#define PACKET_BITS_CHAIN_SINGLE (PACKET_BITS_CHAIN_1|PACKET_BITS_CHAIN_0)
#define PACKET_BITS_ACK_REQ_POS 6
#define PACKET_BITS_ACK_REQ_MASK (0x01<<PACKET_BITS_ACK_REQ_POS)
#define PACKET_BITS_ACK_REQ (PACKET_BITS_ACK_REQ_MASK)
#define ezbus_packet_is_warmboot(packet) (ezbus_packet_type(((packet))) == packet_type_warmboot)
#define ezbus_packet_is_coldboot(packet) (ezbus_packet_type(((packet))) == packet_type_coldboot)
Enumerations
enum ezbus_packet_type_t {
packet_type_reset = 0x00, packet_type_coldboot, packet_type_warmboot_rq, packet_type_warmboot_rp,
packet_type_warmboot_ak, packet_type_take_token, packet_type_give_token, packet_type_parcel,
packet_type_speed, packet_type_ack, packet_type_nack
}
Functions
void ezbus_packet_init (ezbus_packet_t *packet)
void ezbus_packet_deinit (ezbus_packet_t *packet)
void ezbus_packet_set_bits (ezbus_packet_t *packet, uint16_t bits)
void ezbus_packet_set_version (ezbus_packet_t *packet, uint16_t version)
void ezbus_packet_set_chain (ezbus_packet_t *packet, uint16_t chain)
void ezbus_packet_set_ack_req (ezbus_packet_t *packet, uint16_t ack_req)
void ezbus_packet_set_seq (ezbus_packet_t *packet, uint8_t seq)
void ezbus_packet_set_type (ezbus_packet_t *packet, ezbus_packet_type_t type)
void ezbus_packet_set_src (ezbus_packet_t *packet, ezbus_address_t *address)
void ezbus_packet_set_dst (ezbus_packet_t *packet, ezbus_address_t *address)
void ezbus_packet_set_src_socket (ezbus_packet_t *packet, ezbus_socket_t socket)
void ezbus_packet_set_dst_socket (ezbus_packet_t *packet, ezbus_socket_t socket)
void ezbus_packet_set_token_crc (ezbus_packet_t *packet, ezbus_crc_t *crc)
void ezbus_packet_set_token_age (ezbus_packet_t *packet, uint16_t age)
uint16_t ezbus_packet_bits (ezbus_packet_t *packet)
uint16_t ezbus_packet_version (ezbus_packet_t *packet)
uint16_t ezbus_packet_chain (ezbus_packet_t *packet)
uint16_t ezbus_packet_ack_req (ezbus_packet_t *packet)
uint8_t ezbus_packet_seq (ezbus_packet_t *packet)
ezbus_packet_type_t ezbus_packet_type (ezbus_packet_t *packet)
ezbus_address_t * ezbus_packet_dst (ezbus_packet_t *packet)
ezbus_address_t * ezbus_packet_src (ezbus_packet_t *packet)
ezbus_socket_t ezbus_packet_dst_socket (ezbus_packet_t *packet)
ezbus_socket_t ezbus_packet_src_socket (ezbus_packet_t *packet)
ezbus_crc_t * ezbus_packet_get_token_crc (ezbus_packet_t *packet)
uint16_t ezbus_packet_get_token_age (ezbus_packet_t *packet)
uint16_t ezbuf_packet_bytes_to_send (ezbus_packet_t *packet)
void ezbus_packet_flip (ezbus_packet_t *packet)
void ezbus_packet_calc_crc (ezbus_packet_t *packet)
bool ezbus_packet_valid_crc (ezbus_packet_t *packet)
void ezbus_packet_copy (ezbus_packet_t *dst, ezbus_packet_t *src)
bool ezbus_packet_header_valid_crc (ezbus_packet_t *packet)
void ezbus_packet_header_flip (ezbus_packet_t *packet)
bool ezbus_packet_data_valid_crc (ezbus_packet_t *packet)
void ezbus_packet_data_flip (ezbus_packet_t *packet)
uint8_t * ezbus_packet_data (ezbus_packet_t *packet)
uint16_t ezbus_packet_data_size (ezbus_packet_t *packet)
void ezbus_packet_set_parcel (ezbus_packet_t *packet, ezbus_parcel_t *parcel)
void ezbus_packet_get_parcel (ezbus_packet_t *packet, ezbus_parcel_t *parcel)
void ezbus_packet_dump (ezbus_packet_t *packet, const char *prefix)
Macro Definition Documentation
#define ezbus_packet_is_coldboot (packet) (ezbus_packet_type(((packet))) == packet_type_coldboot)
Definition at line 182 of file ezbus_packet.h.
#define ezbus_packet_is_warmboot (packet) (ezbus_packet_type(((packet))) == packet_type_warmboot)
Definition at line 181 of file ezbus_packet.h.
#define PACKET_BITS_ACK_REQ (PACKET_BITS_ACK_REQ_MASK)
Definition at line 53 of file ezbus_packet.h.
Referenced by ezbus_packet_init().
#define PACKET_BITS_ACK_REQ_MASK (0x01<<PACKET_BITS_ACK_REQ_POS)
Definition at line 52 of file ezbus_packet.h.
Referenced by ezbus_packet_ack_req(), and ezbus_packet_set_ack_req().
#define PACKET_BITS_ACK_REQ_POS 6
Definition at line 51 of file ezbus_packet.h.
#define PACKET_BITS_CHAIN_0 (0x01<<PACKET_BITS_CHAIN_POS)
Definition at line 44 of file ezbus_packet.h.
#define PACKET_BITS_CHAIN_1 (0x02<<PACKET_BITS_CHAIN_POS)
Definition at line 45 of file ezbus_packet.h.
#define PACKET_BITS_CHAIN_BEGIN (PACKET_BITS_CHAIN_0)
Definition at line 46 of file ezbus_packet.h.
#define PACKET_BITS_CHAIN_LAST (PACKET_BITS_CHAIN_1)
Definition at line 48 of file ezbus_packet.h.
#define PACKET_BITS_CHAIN_MASK (0x03<<PACKET_BITS_CHAIN_POS)
Definition at line 43 of file ezbus_packet.h.
Referenced by ezbus_packet_chain(), and ezbus_packet_set_chain().
#define PACKET_BITS_CHAIN_MIDDLE (0x00)
Definition at line 47 of file ezbus_packet.h.
#define PACKET_BITS_CHAIN_POS 4
Definition at line 42 of file ezbus_packet.h.
#define PACKET_BITS_CHAIN_SINGLE (PACKET_BITS_CHAIN_1|PACKET_BITS_CHAIN_0)
Definition at line 49 of file ezbus_packet.h.
#define PACKET_BITS_VERSION (PACKET_BITS_VERSION_0)
Definition at line 40 of file ezbus_packet.h.
Referenced by ezbus_packet_init().
#define PACKET_BITS_VERSION_0 (0x01<<PACKET_BITS_VERSION_POS)
Definition at line 36 of file ezbus_packet.h.
#define PACKET_BITS_VERSION_1 (0x02<<PACKET_BITS_VERSION_POS)
Definition at line 37 of file ezbus_packet.h.
#define PACKET_BITS_VERSION_2 (0x04<<PACKET_BITS_VERSION_POS)
Definition at line 38 of file ezbus_packet.h.
#define PACKET_BITS_VERSION_3 (0x08<<PACKET_BITS_VERSION_POS)
Definition at line 39 of file ezbus_packet.h.
#define PACKET_BITS_VERSION_MASK (0x0F<<PACKET_BITS_VERSION_POS)
Definition at line 35 of file ezbus_packet.h.
Referenced by ezbus_packet_set_version(), and ezbus_packet_version().
#define PACKET_BITS_VERSION_POS 0
Definition at line 34 of file ezbus_packet.h.
Enumeration Type Documentation
enum ezbus_packet_type_t
Enumerator
packet_type_reset
packet_type_coldboot
packet_type_warmboot_rq
packet_type_warmboot_rp
packet_type_warmboot_ak
packet_type_take_token
packet_type_give_token
packet_type_parcel
packet_type_speed
packet_type_ack
packet_type_nack
Definition at line 55 of file ezbus_packet.h.
Function Documentation
uint16_t ezbuf_packet_bytes_to_send (ezbus_packet_t * packet)
Definition at line 210 of file ezbus_packet.c.
References ezbus_packet_data_size().
Referenced by ezbus_port_recv(), and ezbus_port_send().
uint16_t ezbus_packet_ack_req (ezbus_packet_t * packet)
Definition at line 131 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, ezbus_packet_t::header, and PACKET_BITS_ACK_REQ_MASK.
Referenced by ezbus_mac_transmitter_reset().
uint16_t ezbus_packet_bits (ezbus_packet_t * packet)
Definition at line 116 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, and ezbus_packet_t::header.
void ezbus_packet_calc_crc (ezbus_packet_t * packet)
Definition at line 174 of file ezbus_packet.c.
References ezbus_header_t::bytes, ezbus_header_t::crc, ezbus_data_t::crc, ezbus_header_t::data, ezbus_packet_t::data, ezbus_crc(), ezbus_crc_init(), ezbus_packet_data(), ezbus_packet_data_size(), and ezbus_packet_t::header.
Referenced by ezbus_port_send().
uint16_t ezbus_packet_chain (ezbus_packet_t * packet)
Definition at line 126 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, ezbus_packet_t::header, and PACKET_BITS_CHAIN_MASK.
void ezbus_packet_copy (ezbus_packet_t * dst, ezbus_packet_t * src)
Definition at line 169 of file ezbus_packet.c.
References ezbus_platform_memcpy().
Referenced by ezbus_mac_receiver_get(), and ezbus_mac_transmitter_put().
uint8_t* ezbus_packet_data (ezbus_packet_t * packet)
Definition at line 217 of file ezbus_packet.c.
References ezbus_data_t::attachment, and ezbus_packet_t::data.
Referenced by ezbus_packet_calc_crc(), ezbus_packet_data_valid_crc(), ezbus_port_receiver_ready(), and ezbus_port_recv().
void ezbus_packet_data_flip (ezbus_packet_t * packet)
Definition at line 273 of file ezbus_packet.c.
References ezbus_data_t::crc, ezbus_packet_t::data, and ezbus_crc_flip().
Referenced by ezbus_packet_flip(), and ezbus_port_recv().
uint16_t ezbus_packet_data_size (ezbus_packet_t * packet)
Definition at line 222 of file ezbus_packet.c.
References ezbus_packet_type(), packet_type_ack, packet_type_coldboot, packet_type_give_token, packet_type_nack, packet_type_parcel, packet_type_reset, packet_type_speed, packet_type_take_token, packet_type_warmboot_ak, packet_type_warmboot_rp, and packet_type_warmboot_rq.
Referenced by ezbuf_packet_bytes_to_send(), ezbus_packet_calc_crc(), ezbus_packet_data_valid_crc(), and ezbus_port_recv().
bool ezbus_packet_data_valid_crc (ezbus_packet_t * packet)
Definition at line 201 of file ezbus_packet.c.
References ezbus_data_t::crc, ezbus_packet_t::data, ezbus_crc(), ezbus_crc_equal(), ezbus_crc_init(), ezbus_packet_data(), and ezbus_packet_data_size().
Referenced by ezbus_packet_valid_crc(), and ezbus_port_recv().
void ezbus_packet_deinit (ezbus_packet_t * packet)
Definition at line 32 of file ezbus_packet.c.
References ezbus_platform_memset().
ezbus_address_t* ezbus_packet_dst (ezbus_packet_t * packet)
Definition at line 148 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, and ezbus_packet_t::header.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_arbiter_receive_signal_token(), and ezbus_packet_set_dst().
ezbus_socket_t ezbus_packet_dst_socket (ezbus_packet_t * packet)
Definition at line 158 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, and ezbus_packet_t::header.
Referenced by ezbus_mac_arbiter_receive_signal_parcel(), ezbus_socket_callback_receiver_ready(), ezbus_socket_callback_transmitter_ack(), and ezbus_socket_callback_transmitter_resend().
void ezbus_packet_dump (ezbus_packet_t * packet, const char * prefix)
Definition at line 278 of file ezbus_packet.c.
References ezbus_header_t::crc, ezbus_header_t::data, ezbus_address_dump(), ezbus_crc_dump(), EZBUS_TMP_BUF_SZ, ezbus_header_t::field, and ezbus_packet_t::header.
void ezbus_packet_flip (ezbus_packet_t * packet)
Definition at line 262 of file ezbus_packet.c.
References ezbus_packet_data_flip(), and ezbus_packet_header_flip().
Referenced by ezbus_port_send().
void ezbus_packet_get_parcel (ezbus_packet_t * packet, ezbus_parcel_t * parcel)
Definition at line 256 of file ezbus_packet.c.
References ezbus_data_t::attachment, ezbus_packet_t::data, ezbus_platform_memcpy(), and ezbus_data_t::parcel.
uint16_t ezbus_packet_get_token_age (ezbus_packet_t * packet)
Definition at line 109 of file ezbus_packet.c.
References ezbus_token_t::age, ezbus_data_t::attachment, ezbus_packet_t::data, and ezbus_data_t::token.
Referenced by ezbus_mac_arbiter_receive_signal_token().
ezbus_crc_t* ezbus_packet_get_token_crc (ezbus_packet_t * packet)
Definition at line 104 of file ezbus_packet.c.
References ezbus_data_t::attachment, ezbus_token_t::crc, ezbus_packet_t::data, and ezbus_data_t::token.
Referenced by ezbus_mac_arbiter_receive_signal_token().
void ezbus_packet_header_flip (ezbus_packet_t * packet)
Definition at line 268 of file ezbus_packet.c.
References ezbus_header_t::crc, ezbus_crc_flip(), and ezbus_packet_t::header.
Referenced by ezbus_packet_flip(), and ezbus_port_recv().
bool ezbus_packet_header_valid_crc (ezbus_packet_t * packet)
Definition at line 194 of file ezbus_packet.c.
References ezbus_header_t::bytes, ezbus_header_t::crc, ezbus_header_t::data, ezbus_crc(), ezbus_crc_equal(), ezbus_crc_init(), and ezbus_packet_t::header.
Referenced by ezbus_packet_valid_crc(), and ezbus_port_recv().
void ezbus_packet_init (ezbus_packet_t * packet)
Definition at line 25 of file ezbus_packet.c.
References ezbus_packet_set_ack_req(), ezbus_packet_set_version(), ezbus_platform_memset(), PACKET_BITS_ACK_REQ, and PACKET_BITS_VERSION.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_warmboot_signal_stop(), ezbus_port_transmitter_empty(), and ezbuz_mac_arbiter_transmit_token().
uint8_t ezbus_packet_seq (ezbus_packet_t * packet)
Definition at line 136 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, and ezbus_packet_t::header.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), and ezbus_mac_coldboot_signal_continue().
void ezbus_packet_set_ack_req (ezbus_packet_t * packet, uint16_t ack_req)
Definition at line 57 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, ezbus_packet_t::header, and PACKET_BITS_ACK_REQ_MASK.
Referenced by ezbus_packet_init().
void ezbus_packet_set_bits (ezbus_packet_t * packet, uint16_t bits)
Definition at line 40 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, and ezbus_packet_t::header.
void ezbus_packet_set_chain (ezbus_packet_t * packet, uint16_t chain)
Definition at line 51 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, ezbus_packet_t::header, and PACKET_BITS_CHAIN_MASK.
void ezbus_packet_set_dst (ezbus_packet_t * packet, ezbus_address_t * address)
Definition at line 77 of file ezbus_packet.c.
References ezbus_address_copy(), and ezbus_packet_dst().
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_port_transmitter_empty(), and ezbuz_mac_arbiter_transmit_token().
void ezbus_packet_set_dst_socket (ezbus_packet_t * packet, ezbus_socket_t socket)
Definition at line 87 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, and ezbus_packet_t::header.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_warmboot_signal_stop(), and ezbuz_mac_arbiter_transmit_token().
void ezbus_packet_set_parcel (ezbus_packet_t * packet, ezbus_parcel_t * parcel)
Definition at line 251 of file ezbus_packet.c.
References ezbus_data_t::attachment, ezbus_packet_t::data, ezbus_platform_memcpy(), and ezbus_data_t::parcel.
Referenced by ezbus_port_transmitter_empty().
void ezbus_packet_set_seq (ezbus_packet_t * packet, uint8_t seq)
Definition at line 63 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, and ezbus_packet_t::header.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_warmboot_signal_stop(), ezbus_port_transmitter_empty(), and ezbuz_mac_arbiter_transmit_token().
void ezbus_packet_set_src (ezbus_packet_t * packet, ezbus_address_t * address)
Definition at line 73 of file ezbus_packet.c.
References ezbus_address_copy(), and ezbus_packet_src().
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_warmboot_signal_stop(), ezbus_port_transmitter_empty(), and ezbuz_mac_arbiter_transmit_token().
void ezbus_packet_set_src_socket (ezbus_packet_t * packet, ezbus_socket_t socket)
Definition at line 82 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, and ezbus_packet_t::header.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_warmboot_signal_stop(), and ezbuz_mac_arbiter_transmit_token().
void ezbus_packet_set_token_age (ezbus_packet_t * packet, uint16_t age)
Definition at line 99 of file ezbus_packet.c.
References ezbus_token_t::age, ezbus_data_t::attachment, ezbus_packet_t::data, and ezbus_data_t::token.
Referenced by ezbuz_mac_arbiter_transmit_token().
void ezbus_packet_set_token_crc (ezbus_packet_t * packet, ezbus_crc_t * crc)
Definition at line 94 of file ezbus_packet.c.
References ezbus_data_t::attachment, ezbus_token_t::crc, ezbus_packet_t::data, and ezbus_data_t::token.
Referenced by ezbuz_mac_arbiter_transmit_token().
void ezbus_packet_set_type (ezbus_packet_t * packet, ezbus_packet_type_t type)
Definition at line 68 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, and ezbus_packet_t::header.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_warmboot_signal_stop(), ezbus_port_transmitter_empty(), and ezbuz_mac_arbiter_transmit_token().
void ezbus_packet_set_version (ezbus_packet_t * packet, uint16_t version)
Definition at line 45 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, ezbus_packet_t::header, and PACKET_BITS_VERSION_MASK.
Referenced by ezbus_packet_init().
ezbus_address_t* ezbus_packet_src (ezbus_packet_t * packet)
Definition at line 153 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, and ezbus_packet_t::header.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_coldboot_signal_continue(), ezbus_packet_set_src(), and ezbus_socket_callback_receiver_ready().
ezbus_socket_t ezbus_packet_src_socket (ezbus_packet_t * packet)
Definition at line 163 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, and ezbus_packet_t::header.
Referenced by ezbus_mac_arbiter_receive_signal_parcel().
ezbus_packet_type_t ezbus_packet_type (ezbus_packet_t * packet)
Definition at line 141 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, and ezbus_packet_t::header.
Referenced by ezbus_mac_receiver_signal_full(), ezbus_mac_transmitter_reset(), and ezbus_packet_data_size().
bool ezbus_packet_valid_crc (ezbus_packet_t * packet)
Definition at line 185 of file ezbus_packet.c.
References ezbus_packet_data_valid_crc(), and ezbus_packet_header_valid_crc().
uint16_t ezbus_packet_version (ezbus_packet_t * packet)
Definition at line 121 of file ezbus_packet.c.
References ezbus_header_t::data, ezbus_header_t::field, ezbus_packet_t::header, and PACKET_BITS_VERSION_MASK.