EzBus: src/common/ezbus_hex.c File Reference
ezbus_hex.c File Reference
#include <ezbus_hex.h>
#include <ezbus_log.h>
Functions
void ezbus_hex4 (uint8_t nybble, char *hex)
void ezbus_hex8 (uint8_t byte, char *hex)
void ezbus_hex16 (uint16_t word, char *hex)
void ezbus_hex32 (uint32_t word, char *hex)
void ezbus_hex_dump (char *tag, void *data, uint32_t size)
Function Documentation
void ezbus_hex16 (uint16_t word, char * hex)
Definition at line 42 of file ezbus_hex.c.
References ezbus_hex8().
void ezbus_hex32 (uint32_t word, char * hex)
Definition at line 49 of file ezbus_hex.c.
References ezbus_hex8().
void ezbus_hex4 (uint8_t nybble, char * hex)
Definition at line 25 of file ezbus_hex.c.
Referenced by ezbus_hex8().
void ezbus_hex8 (uint8_t byte, char * hex)
Definition at line 35 of file ezbus_hex.c.
References ezbus_hex4().
Referenced by ezbus_address_string(), ezbus_hex16(), ezbus_hex32(), and ezbus_hex_dump().
void ezbus_hex_dump (char * tag, void * data, uint32_t size)
Definition at line 58 of file ezbus_hex.c.
References ezbus_hex8(), ezbus_log(), and EZBUS_LOG_HEX.
Referenced by ezbus_port_recv(), and ezbus_port_send().