EzBus: src/socket/ezbus_socket_callback.c File Reference
ezbus_socket_callback.c File Reference
#include <ezbus_socket_callback.h>
#include <ezbus_socket_common.h>
#include <ezbus_socket.h>
#include <ezbus_port.h>
#include <ezbus_mac_transmitter.h>
#include <ezbus_mac_token.h>
#include <ezbus_mac_peers.h>
#include <ezbus_mac.h>
#include <ezbus_packet.h>
#include <ezbus_parcel.h>
#include <ezbus_log.h>
Functions
bool ezbus_socket_callback_transmitter_empty (ezbus_mac_t *mac)
bool ezbus_socket_callback_transmitter_resend (ezbus_mac_t *mac)
bool ezbus_socket_callback_receiver_ready (ezbus_mac_t *mac, ezbus_packet_t *packet)
void ezbus_socket_callback_transmitter_ack (ezbus_mac_t *mac)
void ezbus_socket_callback_transmitter_limit (ezbus_mac_t *mac)
void ezbus_socket_callback_transmitter_fault (ezbus_mac_t *mac)
void ezbus_socket_callback_receiver_fault (ezbus_mac_t *mac, ezbus_packet_t *packet)
Function Documentation
void ezbus_socket_callback_receiver_fault (ezbus_mac_t * mac, ezbus_packet_t * packet)
Definition at line 129 of file ezbus_socket_callback.c.
References ezbus_log(), and EZBUS_LOG_SOCKET.
bool ezbus_socket_callback_receiver_ready (ezbus_mac_t * mac, ezbus_packet_t * packet)
Definition at line 85 of file ezbus_socket_callback.c.
References ezbus_mac_get_receiver_packet(), ezbus_packet_dst_socket(), ezbus_packet_src(), EZBUS_SOCKET_ANY, ezbus_socket_callback_recv(), and ezbus_socket_open().
Referenced by ezbus_mac_arbiter_receive_signal_parcel().
void ezbus_socket_callback_transmitter_ack (ezbus_mac_t * mac)
Definition at line 104 of file ezbus_socket_callback.c.
References ezbus_log(), EZBUS_LOG_SOCKET, ezbus_mac_get_receiver_packet(), ezbus_packet_dst_socket(), EZBUS_SOCKET_ANY, ezbus_socket_mac(), ezbus_socket_set_tx_seq(), and ezbus_socket_tx_seq().
Referenced by ezbus_mac_arbiter_receive_run().
bool ezbus_socket_callback_transmitter_empty (ezbus_mac_t * mac)
Definition at line 38 of file ezbus_socket_callback.c.
References ezbus_socket_callback_send(), ezbus_socket_is_open(), and ezbus_socket_max().
Referenced by ezbus_mac_arbiter_rst_warmboot_cycles().
void ezbus_socket_callback_transmitter_fault (ezbus_mac_t * mac)
Definition at line 124 of file ezbus_socket_callback.c.
References ezbus_log(), and EZBUS_LOG_SOCKET.
Referenced by ezbus_mac_arbiter_receive_run().
void ezbus_socket_callback_transmitter_limit (ezbus_mac_t * mac)
Definition at line 119 of file ezbus_socket_callback.c.
References ezbus_log(), and EZBUS_LOG_SOCKET.
Referenced by ezbus_mac_transmitter_signal_wait().
bool ezbus_socket_callback_transmitter_resend (ezbus_mac_t * mac)
Definition at line 65 of file ezbus_socket_callback.c.
References ezbus_log(), EZBUS_LOG_SOCKET, ezbus_mac_get_receiver_packet(), ezbus_mac_transmitter_put(), ezbus_packet_dst_socket(), and ezbus_socket_tx_packet().
Referenced by ezbus_mac_transmitter_signal_wait().