EzBus: src/common/ezbus_address.c File Reference
ezbus_address.c File Reference
#include <ezbus_platform.h>
#include <ezbus_address.h>
#include <ezbus_hex.h>
#include <ezbus_log.h>
Functions
void ezbus_address_init (void)
int ezbus_address_compare (const ezbus_address_t *a, const ezbus_address_t *b)
Compare address a vs b.
uint8_t * ezbus_address_copy (ezbus_address_t *dst, const ezbus_address_t *src)
void ezbus_address_swap (ezbus_address_t *dst, ezbus_address_t *src)
char * ezbus_address_string (ezbus_address_t *address)
void ezbus_address_dump (const ezbus_address_t *address, const char *prefix)
Variables
const ezbus_address_t ezbus_broadcast_address
const ezbus_address_t ezbus_warmboot_address
ezbus_address_t ezbus_self_address
Function Documentation
int ezbus_address_compare (const ezbus_address_t * a, const ezbus_address_t * b)
Compare address a vs b.
Returns
<, =, or > 0
Definition at line 53 of file ezbus_address.c.
References ezbus_platform_memcmp().
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_arbiter_receive_signal_token(), ezbus_mac_peers_am_dominant(), ezbus_mac_peers_clean(), ezbus_mac_peers_index_of(), ezbus_mac_peers_insort(), ezbus_mac_peers_next(), and ezbus_port_transmitter_empty().
uint8_t* ezbus_address_copy (ezbus_address_t * dst, const ezbus_address_t * src)
Definition at line 58 of file ezbus_address.c.
References ezbus_platform_memcpy().
Referenced by ezbus_address_swap(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_packet_set_dst(), ezbus_packet_set_src(), and ezbus_peer_init().
void ezbus_address_dump (const ezbus_address_t * address, const char * prefix)
Definition at line 82 of file ezbus_address.c.
References ezbus_address_t::byte, and EZBUS_ADDR_LN.
Referenced by ezbus_packet_dump().
void ezbus_address_init (void)
Definition at line 43 of file ezbus_address.c.
References ezbus_address_string(), ezbus_log(), EZBUS_LOG_ADDRESS, and ezbus_platform_address().
Referenced by ezbus_mac_init().
char* ezbus_address_string (ezbus_address_t * address)
Definition at line 71 of file ezbus_address.c.
References ezbus_address_t::byte, EZBUS_ADDR_LN, EZBUS_ADDR_LN_STR, and ezbus_hex8().
Referenced by ezbus_address_init(), ezbus_mac_arbiter_receive_run(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_peers_log(), and ezbus_peer_string().
void ezbus_address_swap (ezbus_address_t * dst, ezbus_address_t * src)
Definition at line 63 of file ezbus_address.c.
References ezbus_address_copy().
Variable Documentation
const ezbus_address_t ezbus_broadcast_address
Initial value:
=
{
    {0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00}
}
Definition at line 27 of file ezbus_address.c.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_mac_peers_insort(), and ezbus_port_transmitter_empty().
ezbus_address_t ezbus_self_address
Initial value:
=
{
    {0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01}
}
Definition at line 37 of file ezbus_address.c.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_receive_signal_parcel(), ezbus_mac_arbiter_receive_signal_token(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_peers_am_dominant(), ezbus_mac_peers_clean(), ezbus_mac_peers_clear(), ezbus_mac_warmboot_signal_stop(), ezbus_port_transmitter_empty(), and ezbuz_mac_arbiter_transmit_token().
const ezbus_address_t ezbus_warmboot_address
Initial value:
=
{
    {0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF}
}
Definition at line 32 of file ezbus_address.c.
Referenced by ezbus_mac_peers_insort().