EzBus: src/mac/ezbus_mac_warmboot.h File Reference
ezbus_mac_warmboot.h File Reference
#include <ezbus_platform.h>
#include <ezbus_mac.h>
#include <ezbus_timer.h>
#include <ezbus_packet.h>
#include <ezbus_port.h>
#include <ezbus_crc.h>
Classes
struct _ezbus_mac_warmboot_t
Typedefs
typedef struct _ezbus_mac_warmboot_t ezbus_mac_warmboot_t
Enumerations
enum ezbus_mac_warmboot_state_t {
state_warmboot_idle =0, state_warmboot_start, state_warmboot_continue, state_warmboot_stop,
state_warmboot_finished
}
Functions
void ezbus_mac_warmboot_init (ezbus_mac_t *mac)
void ezbus_mac_warmboot_run (ezbus_mac_t *mac)
uint8_t ezbus_mac_warmboot_get_seq (ezbus_mac_t *mac)
void ezbus_mac_warmboot_set_state (ezbus_mac_t *mac, ezbus_mac_warmboot_state_t state)
ezbus_mac_warmboot_state_t ezbus_mac_warmboot_get_state (ezbus_mac_t *mac)
const char * ezbus_mac_warmboot_get_state_str (ezbus_mac_t *mac)
void ezbus_mac_warmboot_signal_idle (ezbus_mac_t *mac)
void ezbus_mac_warmboot_signal_start (ezbus_mac_t *mac)
void ezbus_mac_warmboot_signal_continue (ezbus_mac_t *mac)
void ezbus_mac_warmboot_signal_stop (ezbus_mac_t *mac)
void ezbus_mac_warmboot_signal_finished (ezbus_mac_t *mac)
Typedef Documentation
typedef struct _ezbus_mac_warmboot_t ezbus_mac_warmboot_t
Enumeration Type Documentation
enum ezbus_mac_warmboot_state_t
Enumerator
state_warmboot_idle
state_warmboot_start
state_warmboot_continue
state_warmboot_stop
state_warmboot_finished
Definition at line 33 of file ezbus_mac_warmboot.h.
Function Documentation
uint8_t ezbus_mac_warmboot_get_seq (ezbus_mac_t * mac)
Definition at line 66 of file ezbus_mac_warmboot.c.
References ezbus_mac_get_warmboot(), and _ezbus_mac_warmboot_t::seq.
Referenced by ezbus_mac_warmboot_signal_stop().
ezbus_mac_warmboot_state_t ezbus_mac_warmboot_get_state (ezbus_mac_t * mac)
Definition at line 95 of file ezbus_mac_warmboot.c.
References ezbus_mac_arbiter_dec_warmboot_cycles(), ezbus_mac_arbiter_get_warmboot_cycles(), ezbus_mac_get_warmboot(), ezbus_mac_warmboot_set_state(), ezbus_mac_warmboot_signal_continue(), ezbus_mac_warmboot_signal_finished(), ezbus_mac_warmboot_signal_idle(), ezbus_mac_warmboot_signal_start(), ezbus_mac_warmboot_signal_stop(), ezbus_timer_start, ezbus_timer_stop, _ezbus_mac_warmboot_t::seq, _ezbus_mac_warmboot_t::state, state_warmboot_continue, state_warmboot_finished, state_warmboot_idle, state_warmboot_start, state_warmboot_stop, _ezbus_mac_warmboot_t::warmboot_cycles, and _ezbus_mac_warmboot_t::warmboot_timer.
Referenced by ezbus_mac_warmboot_run().
const char* ezbus_mac_warmboot_get_state_str (ezbus_mac_t * mac)
Definition at line 72 of file ezbus_mac_warmboot.c.
References ezbus_mac_get_warmboot(), _ezbus_mac_warmboot_t::state, state_warmboot_continue, state_warmboot_finished, state_warmboot_idle, state_warmboot_start, and state_warmboot_stop.
void ezbus_mac_warmboot_init (ezbus_mac_t * mac)
Definition at line 37 of file ezbus_mac_warmboot.c.
References ezbus_mac_get_warmboot(), ezbus_platform_memset(), ezbus_timer_init(), ezbus_timer_set_callback(), ezbus_timer_set_key(), ezbus_timer_set_period(), EZBUS_WARMBOOT_TIMER_PERIOD, _ezbus_mac_warmboot_t::seq, and _ezbus_mac_warmboot_t::warmboot_timer.
Referenced by ezbus_mac_init().
void ezbus_mac_warmboot_run (ezbus_mac_t * mac)
Definition at line 52 of file ezbus_mac_warmboot.c.
References ezbus_mac_get_warmboot(), ezbus_mac_warmboot_get_state(), ezbus_timer_run(), state_warmboot_continue, state_warmboot_finished, state_warmboot_idle, state_warmboot_start, state_warmboot_stop, and _ezbus_mac_warmboot_t::warmboot_timer.
Referenced by ezbus_mac_run().
void ezbus_mac_warmboot_set_state (ezbus_mac_t * mac, ezbus_mac_warmboot_state_t state)
Definition at line 88 of file ezbus_mac_warmboot.c.
References ezbus_mac_get_warmboot(), and _ezbus_mac_warmboot_t::state.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_mac_coldboot_signal_dominant(), ezbus_mac_coldboot_signal_start(), ezbus_mac_warmboot_get_state(), and ezbus_mac_warmboot_signal_finished().
void ezbus_mac_warmboot_signal_continue (ezbus_mac_t * mac)
Definition at line 121 of file ezbus_mac_arbiter_transmit.c.
Referenced by ezbus_mac_warmboot_get_state().
void ezbus_mac_warmboot_signal_finished (ezbus_mac_t * mac)
END RECEIVE PARCEL
Definition at line 318 of file ezbus_mac_arbiter.c.
References ezbus_log(), EZBUS_LOG_WARMBOOT, ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_mac_arbiter_set_state(), ezbus_mac_token_acquire(), ezbus_mac_token_reset(), ezbus_mac_warmboot_set_state(), mac_arbiter_state_service_start, and state_warmboot_start.
Referenced by ezbus_mac_warmboot_get_state().
void ezbus_mac_warmboot_signal_idle (ezbus_mac_t * mac)
Definition at line 146 of file ezbus_mac_arbiter_transmit.c.
Referenced by ezbus_mac_warmboot_get_state().
void ezbus_mac_warmboot_signal_start (ezbus_mac_t * mac)
Definition at line 116 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), and EZBUS_LOG_WARMBOOT.
Referenced by ezbus_mac_warmboot_get_state().
void ezbus_mac_warmboot_signal_stop (ezbus_mac_t * mac)
Definition at line 126 of file ezbus_mac_arbiter_transmit.c.
References ezbus_log(), EZBUS_LOG_WARMBOOT, ezbus_mac_coldboot_set_state(), ezbus_mac_transmitter_empty, ezbus_mac_transmitter_put(), ezbus_mac_warmboot_get_seq(), ezbus_packet_init(), ezbus_packet_set_dst_socket(), ezbus_packet_set_seq(), ezbus_packet_set_src(), ezbus_packet_set_src_socket(), ezbus_packet_set_type(), ezbus_self_address, EZBUS_SOCKET_ANY, packet_type_warmboot_rq, and state_coldboot_silent_start.
Referenced by ezbus_mac_warmboot_get_state().