EzBus: src/common/ezbus_port.c File Reference
ezbus_port.c File Reference
#include <ezbus_port.h>
#include <ezbus_packet.h>
#include <ezbus_hex.h>
#include <ezbus_log.h>
Functions
void ezbus_port_init_struct (ezbus_port_t *port)
EZBUS_ERR ezbus_port_open (ezbus_port_t *port, uint32_t speed)
EZBUS_ERR ezbus_port_send (ezbus_port_t *port, ezbus_packet_t *packet)
EZBUS_ERR ezbus_port_recv (ezbus_port_t *port, ezbus_packet_t *packet)
int ezbus_port_getch (ezbus_port_t *port)
void ezbus_port_close (ezbus_port_t *port)
void ezbus_port_drain (ezbus_port_t *port)
void ezbus_port_set_speed (ezbus_port_t *port, uint32_t speed)
uint32_t ezbus_port_get_speed (ezbus_port_t *port)
uint32_t ezbus_port_byte_time_ns (ezbus_port_t *port)
uint32_t ezbus_port_packet_timeout_time_ms (ezbus_port_t *port)
void ezbus_port_dump (ezbus_port_t *port, const char *prefix)
Variables
uint32_t ezbus_port_speeds [EZBUS_SPEED_COUNT]
Function Documentation
uint32_t ezbus_port_byte_time_ns (ezbus_port_t * port)
Definition at line 205 of file ezbus_port.c.
References ezbus_port_t::speed.
Referenced by ezbus_port_packet_timeout_time_ms().
void ezbus_port_close (ezbus_port_t * port)
Definition at line 183 of file ezbus_port.c.
References ezbus_platform_close(), and ezbus_port_t::platform_port.
void ezbus_port_drain (ezbus_port_t * port)
Definition at line 188 of file ezbus_port.c.
References ezbus_platform_drain(), and ezbus_port_t::platform_port.
void ezbus_port_dump (ezbus_port_t * port, const char * prefix)
Definition at line 222 of file ezbus_port.c.
References ezbus_platform_port_dump(), EZBUS_TMP_BUF_SZ, ezbus_port_t::packet_timeout, ezbus_port_t::platform_port, ezbus_port_t::rx_err_crc_count, ezbus_port_t::rx_err_overrun_count, ezbus_port_t::rx_err_timeout_count, ezbus_port_t::speed, ezbus_port_t::tx_err_overrun_count, and ezbus_port_t::tx_err_retry_fail_count.
uint32_t ezbus_port_get_speed (ezbus_port_t * port)
Definition at line 200 of file ezbus_port.c.
References ezbus_port_t::speed.
Referenced by ezbus_mac_token_ring_time().
int ezbus_port_getch (ezbus_port_t * port)
Definition at line 178 of file ezbus_port.c.
References ezbus_platform_getc(), and ezbus_port_t::platform_port.
Referenced by ezbus_port_send().
void ezbus_port_init_struct (ezbus_port_t * port)
Definition at line 42 of file ezbus_port.c.
References ezbus_platform_memset().
EZBUS_ERR ezbus_port_open (ezbus_port_t * port, uint32_t speed)
Definition at line 48 of file ezbus_port.c.
References EZBUS_ERR_IO, EZBUS_ERR_OKAY, ezbus_platform_open(), ezbus_port_packet_timeout_time_ms(), ezbus_port_t::packet_timeout, ezbus_port_t::platform_port, ezbus_port_t::rx_err_crc_count, ezbus_port_t::rx_err_overrun_count, ezbus_port_t::rx_err_timeout_count, ezbus_port_t::speed, and ezbus_port_t::tx_err_overrun_count.
uint32_t ezbus_port_packet_timeout_time_ms (ezbus_port_t * port)
Definition at line 213 of file ezbus_port.c.
References ezbus_port_byte_time_ns().
Referenced by ezbus_port_open(), and ezbus_port_set_speed().
EZBUS_ERR ezbus_port_recv (ezbus_port_t * port, ezbus_packet_t * packet)
Definition at line 116 of file ezbus_port.c.
References ezbus_data_t::crc, ezbus_packet_t::data, ezbuf_packet_bytes_to_send(), EZBUS_ERR_CRC, EZBUS_ERR_NOTREADY, EZBUS_ERR_OKAY, EZBUS_ERR_TIMEOUT, ezbus_hex_dump(), EZBUS_MARK, ezbus_packet_data(), ezbus_packet_data_flip(), ezbus_packet_data_size(), ezbus_packet_data_valid_crc(), ezbus_packet_header_flip(), ezbus_packet_header_valid_crc(), and ezbus_packet_t::header.
Referenced by ezbus_mac_receiver_get().
EZBUS_ERR ezbus_port_send (ezbus_port_t * port, ezbus_packet_t * packet)
Definition at line 64 of file ezbus_port.c.
References ezbus_header_t::data, ezbuf_packet_bytes_to_send(), EZBUS_ERR_IO, EZBUS_ERR_OKAY, ezbus_hex_dump(), EZBUS_MARK, ezbus_packet_calc_crc(), ezbus_packet_flip(), ezbus_platform_flush(), ezbus_platform_get_ms_ticks(), ezbus_platform_send(), ezbus_port_getch(), ezbus_header_t::field, ezbus_packet_t::header, ezbus_port_t::packet_timeout, and ezbus_port_t::platform_port.
Referenced by ezbus_mac_transmitter_reset().
void ezbus_port_set_speed (ezbus_port_t * port, uint32_t speed)
Definition at line 193 of file ezbus_port.c.
References ezbus_platform_set_speed(), ezbus_port_packet_timeout_time_ms(), ezbus_port_t::packet_timeout, ezbus_port_t::platform_port, and ezbus_port_t::speed.
Variable Documentation
uint32_t ezbus_port_speeds[EZBUS_SPEED_COUNT]
Initial value:
= {   2400,
                                                    9600,
                                                    57600,
                                                    115200,
                                                    460800,
                                                    921600,
                                                    2000000,
                                                    3000000,
                                                    5000000,
                                                    10000000 }
Definition at line 30 of file ezbus_port.c.