EzBus: src/common/ezbus_timer.h File Reference
ezbus_timer.h File Reference
#include <ezbus_platform.h>
Classes
struct _ezbus_timer_t
Macros
#define ezbus_timer_start(timer) ezbus_timer_set_state((timer),state_timer_starting)
#define ezbus_timer_restart(timer) ezbus_timer_set_state((timer),state_timer_starting)
#define ezbus_timer_stop(timer) ezbus_timer_set_state((timer),state_timer_stopping)
#define ezbus_timer_stopped(timer) (ezbus_timer_get_state((timer))==state_timer_stopped)
#define ezbus_timer_pause(timer) ezbus_timer_set_state((timer),state_timer_pausing)
#define ezbus_timer_resume(timer) ezbus_timer_set_state((timer),state_timer_resuming)
#define ezbus_timer_expired(timer) (ezbus_timer_get_state((timer))==state_timer_expired)
Typedefs
typedef struct _ezbus_timer_t ezbus_timer_t
typedef void(* ezbus_timer_callback_t) (struct _ezbus_timer_t *, void *)
Enumerations
enum ezbus_timer_state_t {
state_timer_stopping =0, state_timer_stopped, state_timer_starting, state_timer_started,
state_timer_pausing, state_timer_paused, state_timer_resuming, state_timer_resume,
state_timer_expiring, state_timer_expired
}
Functions
void ezbus_timer_init (ezbus_timer_t *timer)
void ezbus_timer_run (ezbus_timer_t *timer)
void ezbus_timer_set_state (ezbus_timer_t *timer, ezbus_timer_state_t state)
ezbus_timer_state_t ezbus_timer_get_state (ezbus_timer_t *timer)
void ezbus_timer_set_period (ezbus_timer_t *timer, ezbus_ms_tick_t period)
ezbus_ms_tick_t ezbus_timer_get_period (ezbus_timer_t *timer)
void ezbus_timer_set_callback (ezbus_timer_t *timer, ezbus_timer_callback_t callback, void *arg)
ezbus_ms_tick_t ezbus_timer_get_ticks (ezbus_timer_t *timer)
void ezbus_timer_set_key (ezbus_timer_t *timer, char *key)
char * eabus_timer_get_key (ezbus_timer_t *timer)
Macro Definition Documentation
#define ezbus_timer_expired (timer) (ezbus_timer_get_state((timer))==state_timer_expired)
Definition at line 74 of file ezbus_timer.h.
Referenced by ezbus_mac_coldboot_get_state().
#define ezbus_timer_pause (timer) ezbus_timer_set_state((timer),state_timer_pausing)
Definition at line 72 of file ezbus_timer.h.
#define ezbus_timer_restart (timer) ezbus_timer_set_state((timer),state_timer_starting)
Definition at line 69 of file ezbus_timer.h.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_token_acquire(), ezbus_mac_token_acquired(), ezbus_mac_token_relinquish(), ezbus_mac_token_reset(), and ezbus_mac_transmitter_signal_wait().
#define ezbus_timer_resume (timer) ezbus_timer_set_state((timer),state_timer_resuming)
Definition at line 73 of file ezbus_timer.h.
#define ezbus_timer_start (timer) ezbus_timer_set_state((timer),state_timer_starting)
Definition at line 68 of file ezbus_timer.h.
Referenced by ezbus_mac_coldboot_get_state(), and ezbus_mac_warmboot_get_state().
#define ezbus_timer_stop (timer) ezbus_timer_set_state((timer),state_timer_stopping)
Definition at line 70 of file ezbus_timer.h.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_transmit_reset(), ezbus_mac_coldboot_get_state(), and ezbus_mac_warmboot_get_state().
#define ezbus_timer_stopped (timer) (ezbus_timer_get_state((timer))==state_timer_stopped)
Definition at line 71 of file ezbus_timer.h.
Typedef Documentation
typedef void(* ezbus_timer_callback_t) (struct _ezbus_timer_t *, void *)
Definition at line 55 of file ezbus_timer.h.
typedef struct _ezbus_timer_t ezbus_timer_t
Enumeration Type Documentation
enum ezbus_timer_state_t
Enumerator
state_timer_stopping
state_timer_stopped
state_timer_starting
state_timer_started
state_timer_pausing
state_timer_paused
state_timer_resuming
state_timer_resume
state_timer_expiring
state_timer_expired
Definition at line 31 of file ezbus_timer.h.
Function Documentation
char* eabus_timer_get_key (ezbus_timer_t * timer)
Definition at line 86 of file ezbus_timer.c.
References _ezbus_timer_t::key.
Referenced by ezbus_timer_run().
ezbus_ms_tick_t ezbus_timer_get_period (ezbus_timer_t * timer)
Definition at line 97 of file ezbus_timer.c.
References _ezbus_timer_t::period.
ezbus_timer_state_t ezbus_timer_get_state (ezbus_timer_t * timer)
Definition at line 76 of file ezbus_timer.c.
References _ezbus_timer_t::state.
ezbus_ms_tick_t ezbus_timer_get_ticks (ezbus_timer_t * timer)
Definition at line 108 of file ezbus_timer.c.
References ezbus_platform_get_ms_ticks(), ezbus_timer_get_ticks(), and _ezbus_timer_t::period.
Referenced by ezbus_timer_get_ticks(), and ezbus_timer_run().
void ezbus_timer_init (ezbus_timer_t * timer)
Definition at line 28 of file ezbus_timer.c.
References ezbus_platform_memset().
Referenced by ezbus_mac_arbiter_receive_init(), ezbus_mac_arbiter_transmit_init(), ezbus_mac_coldboot_init(), ezbus_mac_token_init(), and ezbus_mac_warmboot_init().
void ezbus_timer_run (ezbus_timer_t * timer)
Definition at line 33 of file ezbus_timer.c.
References _ezbus_timer_t::arg, _ezbus_timer_t::callback, eabus_timer_get_key(), ezbus_log(), EZBUS_LOG_TIMERS, ezbus_timer_get_ticks(), ezbus_timer_set_state(), _ezbus_timer_t::start, _ezbus_timer_t::state, state_timer_expired, state_timer_expiring, state_timer_paused, state_timer_pausing, state_timer_resume, state_timer_resuming, state_timer_started, state_timer_starting, state_timer_stopped, and state_timer_stopping.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_transmit_run(), ezbus_mac_coldboot_run(), ezbus_mac_token_run(), and ezbus_mac_warmboot_run().
void ezbus_timer_set_callback (ezbus_timer_t * timer, ezbus_timer_callback_t callback, void * arg)
Definition at line 102 of file ezbus_timer.c.
References _ezbus_timer_t::arg, and _ezbus_timer_t::callback.
Referenced by ezbus_mac_arbiter_receive_init(), ezbus_mac_arbiter_transmit_init(), ezbus_mac_coldboot_init(), ezbus_mac_token_init(), and ezbus_mac_warmboot_init().
void ezbus_timer_set_key (ezbus_timer_t * timer, char * key)
Definition at line 81 of file ezbus_timer.c.
References _ezbus_timer_t::key.
Referenced by ezbus_mac_arbiter_receive_init(), ezbus_mac_arbiter_transmit_init(), ezbus_mac_coldboot_init(), ezbus_mac_token_init(), and ezbus_mac_warmboot_init().
void ezbus_timer_set_period (ezbus_timer_t * timer, ezbus_ms_tick_t period)
Definition at line 92 of file ezbus_timer.c.
References _ezbus_timer_t::period.
Referenced by ezbus_mac_arbiter_receive_init(), ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_transmit_init(), ezbus_mac_coldboot_get_state(), ezbus_mac_token_init(), ezbus_mac_token_run(), and ezbus_mac_warmboot_init().
void ezbus_timer_set_state (ezbus_timer_t * timer, ezbus_timer_state_t state)
Definition at line 71 of file ezbus_timer.c.
References _ezbus_timer_t::state.
Referenced by ezbus_timer_run().