EzBus: src/platform/ezbus_platform_linux.c File Reference
ezbus_platform_linux.c File Reference
#include <ezbus_platform.h>
#include <ezbus_address.h>
#include <linux/serial.h>
#include <sys/ioctl.h>
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/time.h>
#include <errno.h>
#include <stdbool.h>
#include <time.h>
#include <sys/select.h>
#include <asm/termbits.h>
#include <ezbus_hex.h>
Macros
#define EZBUS_PACKET_DEBUG 1
Functions
int ezbus_platform_open (ezbus_platform_port_t *port, uint32_t speed)
int ezbus_platform_send (ezbus_platform_port_t *port, void *bytes, size_t size)
int ezbus_platform_recv (ezbus_platform_port_t *port, void *bytes, size_t size)
int ezbus_platform_getc (ezbus_platform_port_t *port)
void ezbus_platform_close (ezbus_platform_port_t *port)
void ezbus_platform_drain (ezbus_platform_port_t *port)
int ezbus_platform_set_speed (ezbus_platform_port_t *port, uint32_t baud)
void ezbus_platform_flush (ezbus_platform_port_t *port)
void * ezbus_platform_memset (void *dest, int c, size_t n)
void * ezbus_platform_memcpy (void *dest, const void *src, size_t n)
void * ezbus_platform_memmove (void *dest, const void *src, size_t n)
int ezbus_platform_memcmp (const void *dest, const void *src, size_t n)
char * ezbus_platform_strcpy (char *dest, const char *src)
char * ezbus_platform_strcat (char *dest, const char *src)
char * ezbus_platform_strncpy (char *dest, const char *src, size_t n)
size_t ezbus_platform_strlen (const char *s)
void * ezbus_platform_malloc (size_t n)
void * ezbus_platform_realloc (void *src, size_t n)
void ezbus_platform_free (void *src)
ezbus_ms_tick_t ezbus_platform_get_ms_ticks ()
void ezbus_platform_set_address (void *address, size_t size)
void ezbus_platform_address (void *address)
int ezbus_platform_rand (void)
void ezbus_platform_srand (unsigned int seed)
int ezbus_platform_random (int lower, int upper)
void ezbus_platform_rand_init (void)
void ezbus_platform_delay (unsigned int ms)
void ezbus_platform_port_dump (ezbus_platform_port_t *platform_port, const char *prefix)
Macro Definition Documentation
#define EZBUS_PACKET_DEBUG 1
Definition at line 42 of file ezbus_platform_linux.c.
Function Documentation
void ezbus_platform_address (void * address)
Definition at line 213 of file ezbus_platform_linux.c.
References ezbus_platform_rand(), ezbus_platform_srand(), and ezbus_address_t::word.
Referenced by ezbus_address_init().
void ezbus_platform_close (ezbus_platform_port_t * port)
Definition at line 97 of file ezbus_platform_linux.c.
References ezbus_platform_port_t::fd.
Referenced by ezbus_port_close().
void ezbus_platform_delay (unsigned int ms)
Definition at line 274 of file ezbus_platform_linux.c.
References ezbus_platform_get_ms_ticks().
void ezbus_platform_drain (ezbus_platform_port_t * port)
Definition at line 102 of file ezbus_platform_linux.c.
References ezbus_platform_getc().
Referenced by ezbus_port_drain().
void ezbus_platform_flush (ezbus_platform_port_t * port)
Definition at line 139 of file ezbus_platform_linux.c.
References ezbus_platform_port_t::fd.
Referenced by ezbus_port_send().
void ezbus_platform_free (void * src)
Definition at line 194 of file ezbus_platform_linux.c.
ezbus_ms_tick_t ezbus_platform_get_ms_ticks ()
Definition at line 199 of file ezbus_platform_linux.c.
Referenced by ezbus_platform_delay(), ezbus_platform_rand_init(), ezbus_port_receiver_ready(), ezbus_port_send(), and ezbus_timer_get_ticks().
int ezbus_platform_getc (ezbus_platform_port_t * port)
Definition at line 86 of file ezbus_platform_linux.c.
References ezbus_platform_port_t::fd.
Referenced by ezbus_platform_drain(), and ezbus_port_getch().
void* ezbus_platform_malloc (size_t n)
Definition at line 184 of file ezbus_platform_linux.c.
int ezbus_platform_memcmp (const void * dest, const void * src, size_t n)
Definition at line 159 of file ezbus_platform_linux.c.
Referenced by ezbus_address_compare(), and ezbus_peer_compare().
void* ezbus_platform_memcpy (void * dest, const void * src, size_t n)
Definition at line 149 of file ezbus_platform_linux.c.
Referenced by ezbus_address_copy(), ezbus_packet_copy(), ezbus_packet_get_parcel(), ezbus_packet_set_parcel(), ezbus_parcel_copy(), ezbus_parcel_get_data(), ezbus_parcel_set_data(), ezbus_peer_copy(), and ezbus_platform_set_address().
void* ezbus_platform_memmove (void * dest, const void * src, size_t n)
Definition at line 154 of file ezbus_platform_linux.c.
Referenced by ezbus_mac_peers_dump(), and ezbus_mac_peers_take().
void* ezbus_platform_memset (void * dest, int c, size_t n)
Definition at line 144 of file ezbus_platform_linux.c.
Referenced by ezbus_mac_coldboot_init(), ezbus_mac_peers_clear(), ezbus_mac_receiver_init(), ezbus_mac_transmitter_init(), ezbus_mac_warmboot_init(), ezbus_packet_deinit(), ezbus_packet_init(), ezbus_parcel_init(), ezbus_port_init_struct(), ezbus_socket_init(), ezbus_socket_open(), ezbus_socket_recv(), ezbus_string_init(), ezbus_string_set_length(), and ezbus_timer_init().
int ezbus_platform_open (ezbus_platform_port_t * port, uint32_t speed)
Definition at line 48 of file ezbus_platform_linux.c.
References ezbus_platform_set_speed(), ezbus_platform_port_t::fd, and ezbus_platform_port_t::serial_port_name.
Referenced by ezbus_port_open().
void ezbus_platform_port_dump (ezbus_platform_port_t * platform_port, const char * prefix)
Definition at line 280 of file ezbus_platform_linux.c.
References ezbus_platform_port_t::dir_pin, ezbus_platform_port_t::fd, ezbus_platform_port_t::serial_port_name, and ezbus_platform_port_t::serial_port_no.
int ezbus_platform_rand (void)
Definition at line 253 of file ezbus_platform_linux.c.
Referenced by ezbus_platform_address().
void ezbus_platform_rand_init (void)
Definition at line 269 of file ezbus_platform_linux.c.
References ezbus_platform_get_ms_ticks(), and ezbus_platform_srand().
int ezbus_platform_random (int lower, int upper)
Definition at line 263 of file ezbus_platform_linux.c.
Referenced by ezbus_mac_arbiter_receive_run(), and ezbus_mac_coldboot_get_state().
void* ezbus_platform_realloc (void * src, size_t n)
Definition at line 189 of file ezbus_platform_linux.c.
Referenced by ezbus_string_cat(), and ezbus_string_set_length().
int ezbus_platform_recv (ezbus_platform_port_t * port, void * bytes, size_t size)
Definition at line 80 of file ezbus_platform_linux.c.
References ezbus_platform_port_t::fd.
int ezbus_platform_send (ezbus_platform_port_t * port, void * bytes, size_t size)
Definition at line 67 of file ezbus_platform_linux.c.
References ezbus_platform_port_t::fd.
Referenced by ezbus_port_send().
void ezbus_platform_set_address (void * address, size_t size)
Definition at line 208 of file ezbus_platform_linux.c.
References ezbus_platform_memcpy().
int ezbus_platform_set_speed (ezbus_platform_port_t * port, uint32_t baud)
Definition at line 107 of file ezbus_platform_linux.c.
References ezbus_platform_port_t::fd.
Referenced by ezbus_platform_open(), and ezbus_port_set_speed().
void ezbus_platform_srand (unsigned int seed)
Definition at line 258 of file ezbus_platform_linux.c.
Referenced by ezbus_platform_address(), and ezbus_platform_rand_init().
char* ezbus_platform_strcat (char * dest, const char * src)
Definition at line 169 of file ezbus_platform_linux.c.
Referenced by ezbus_string_cat().
char* ezbus_platform_strcpy (char * dest, const char * src)
Definition at line 164 of file ezbus_platform_linux.c.
Referenced by ezbus_port_transmitter_empty(), and ezbus_string_copy().
size_t ezbus_platform_strlen (const char * s)
Definition at line 179 of file ezbus_platform_linux.c.
Referenced by ezbus_parcel_get_string(), ezbus_parcel_set_string(), ezbus_string_from_c(), and ezbus_string_length().
char* ezbus_platform_strncpy (char * dest, const char * src, size_t n)
Definition at line 174 of file ezbus_platform_linux.c.
Referenced by ezbus_parcel_get_string(), ezbus_parcel_set_string(), ezbus_string_from_c(), ezbus_string_left(), ezbus_string_right(), and ezbus_string_to_c().