EzBus: src/mac/ezbus_mac_coldboot.c File Reference
ezbus_mac_coldboot.c File Reference
#include <ezbus_mac_coldboot.h>
#include <ezbus_mac_peers.h>
#include <ezbus_mac_token.h>
#include <ezbus_hex.h>
#include <ezbus_log.h>
#include <ezbus_timer.h>
Macros
#define ezbus_mac_coldboot_set_emit_count(boot, c) ((boot)->emit_count=(c))
#define ezbus_mac_coldboot_get_emit_count(boot) ((boot)->emit_count)
#define ezbus_mac_coldboot_inc_emit_count(boot) ezbus_mac_coldboot_set_emit_count(boot,ezbus_mac_coldboot_get_emit_count(boot)+1)
#define ezbus_mac_coldboot_set_emit_seq(boot, c) ((boot)->emit_count=(c))
#define ezbus_mac_coldboot_get_emit_seq(boot) ((boot)->emit_count)
#define ezbus_mac_coldboot_inc_emit_seq(boot) ezbus_mac_coldboot_set_emit_count(boot,ezbus_mac_coldboot_get_emit_count(boot)+1)
Functions
void ezbus_mac_coldboot_init (ezbus_mac_t *mac)
void ezbus_mac_coldboot_run (ezbus_mac_t *mac)
uint8_t ezbus_mac_coldboot_get_seq (ezbus_mac_t *mac)
const char * ezbus_mac_coldboot_get_state_str (ezbus_mac_t *mac)
void ezbus_mac_coldboot_set_state (ezbus_mac_t *mac, ezbus_mac_coldboot_state_t state)
ezbus_mac_coldboot_state_t ezbus_mac_coldboot_get_state (ezbus_mac_t *mac)
Macro Definition Documentation
#define ezbus_mac_coldboot_get_emit_count (boot) ((boot)->emit_count)
Definition at line 30 of file ezbus_mac_coldboot.c.
Referenced by ezbus_mac_coldboot_get_state().
#define ezbus_mac_coldboot_get_emit_seq (boot) ((boot)->emit_count)
Definition at line 34 of file ezbus_mac_coldboot.c.
#define ezbus_mac_coldboot_inc_emit_count (boot) ezbus_mac_coldboot_set_emit_count(boot,ezbus_mac_coldboot_get_emit_count(boot)+1)
Definition at line 31 of file ezbus_mac_coldboot.c.
Referenced by ezbus_mac_coldboot_get_state().
#define ezbus_mac_coldboot_inc_emit_seq (boot) ezbus_mac_coldboot_set_emit_count(boot,ezbus_mac_coldboot_get_emit_count(boot)+1)
Definition at line 35 of file ezbus_mac_coldboot.c.
#define ezbus_mac_coldboot_set_emit_count (boot, c) ((boot)->emit_count=(c))
Definition at line 29 of file ezbus_mac_coldboot.c.
Referenced by ezbus_mac_coldboot_get_state().
#define ezbus_mac_coldboot_set_emit_seq (boot, c) ((boot)->emit_count=(c))
Definition at line 33 of file ezbus_mac_coldboot.c.
Function Documentation
uint8_t ezbus_mac_coldboot_get_seq (ezbus_mac_t * mac)
Definition at line 87 of file ezbus_mac_coldboot.c.
References ezbus_mac_get_coldboot(), and _ezbus_mac_coldboot_t::seq.
Referenced by ezbus_mac_coldboot_signal_continue().
ezbus_mac_coldboot_state_t ezbus_mac_coldboot_get_state (ezbus_mac_t * mac)
Definition at line 120 of file ezbus_mac_coldboot.c.
References _ezbus_mac_coldboot_t::coldboot_timer, EZBUS_COLDBOOT_CYCLES, EZBUS_COLDBOOT_SILENT_TIME, EZBUS_COLDBOOT_TIMER_MAX, EZBUS_COLDBOOT_TIMER_MIN, ezbus_mac_coldboot_get_emit_count, ezbus_mac_coldboot_inc_emit_count, ezbus_mac_coldboot_set_emit_count, ezbus_mac_coldboot_set_state(), ezbus_mac_coldboot_signal_continue(), ezbus_mac_coldboot_signal_dominant(), ezbus_mac_coldboot_signal_silent_continue(), ezbus_mac_coldboot_signal_silent_start(), ezbus_mac_coldboot_signal_silent_stop(), ezbus_mac_coldboot_signal_start(), ezbus_mac_coldboot_signal_stop(), ezbus_mac_get_coldboot(), ezbus_mac_token_ring_time(), ezbus_platform_random(), ezbus_timer_expired, ezbus_timer_set_period(), ezbus_timer_start, ezbus_timer_stop, _ezbus_mac_coldboot_t::seq, _ezbus_mac_coldboot_t::silent_timer, _ezbus_mac_coldboot_t::state, state_coldboot_continue, state_coldboot_dominant, state_coldboot_silent_continue, state_coldboot_silent_start, state_coldboot_silent_stop, and state_coldboot_start.
Referenced by ezbus_mac_arbiter_receive_run(), and ezbus_mac_coldboot_run().
const char* ezbus_mac_coldboot_get_state_str (ezbus_mac_t * mac)
Definition at line 93 of file ezbus_mac_coldboot.c.
References ezbus_mac_get_coldboot(), _ezbus_mac_coldboot_t::state, state_coldboot_continue, state_coldboot_dominant, state_coldboot_silent_continue, state_coldboot_silent_start, state_coldboot_silent_stop, state_coldboot_start, and state_coldboot_stop.
void ezbus_mac_coldboot_init (ezbus_mac_t * mac)
Definition at line 50 of file ezbus_mac_coldboot.c.
References _ezbus_mac_coldboot_t::coldboot_timer, ezbus_mac_get_coldboot(), ezbus_platform_memset(), ezbus_timer_init(), ezbus_timer_set_callback(), ezbus_timer_set_key(), and _ezbus_mac_coldboot_t::silent_timer.
Referenced by ezbus_mac_init().
void ezbus_mac_coldboot_run (ezbus_mac_t * mac)
Definition at line 66 of file ezbus_mac_coldboot.c.
References _ezbus_mac_coldboot_t::coldboot_timer, ezbus_mac_coldboot_get_state(), ezbus_mac_get_coldboot(), ezbus_timer_run(), _ezbus_mac_coldboot_t::silent_timer, state_coldboot_continue, state_coldboot_dominant, state_coldboot_silent_continue, state_coldboot_silent_start, state_coldboot_silent_stop, state_coldboot_start, and state_coldboot_stop.
Referenced by ezbus_mac_run().
void ezbus_mac_coldboot_set_state (ezbus_mac_t * mac, ezbus_mac_coldboot_state_t state)
Definition at line 113 of file ezbus_mac_coldboot.c.
References ezbus_mac_get_coldboot(), and _ezbus_mac_coldboot_t::state.
Referenced by ezbus_mac_arbiter_receive_run(), ezbus_mac_arbiter_rst_warmboot_cycles(), ezbus_mac_coldboot_get_state(), ezbus_mac_coldboot_signal_dominant(), and ezbus_mac_warmboot_signal_stop().