EzBus: src/socket/ezbus_socket.h File Reference
ezbus_socket.h File Reference
#include <ezbus_platform.h>
#include <ezbus_packet.h>
#include <ezbus_mac.h>
#include <ezbus_fault.h>
Functions
bool ezbus_socket_callback_send (ezbus_socket_t socket)
This API implements an interface for using transciever channels to exchange data packets with other ezbus nodes. Such a channel is termed a socket. One socket replresents a signular tranceiver channel between this node, and a single peer. A socket must be 'opened' before it can be used. See ezbus_socket_open() for more details. In the case that an unsolicited parcel packet arrives from a peer (socket==EXBUS_SICKET_ANY), a local socket will automatically be opened prior to ezbus_socket_callback_recv() being invoked. The socket remain opened until closed by the consumer of this API. Be sure to review ezbus_socket_init(), ezbus_socket_callback_send() and ezbus_socket_callback_recv()
bool ezbus_socket_callback_recv (ezbus_socket_t socket)
The consumer of this API is required to implement ezbus_socket_callback_recv(), see ezbus_socket_recv() for details.
void ezbus_socket_init (void)
Initializes the socket layer, and must be invoked once prior to using any socket functions Invocation must take place from with the thre ad context of the consumer of the API.
int ezbus_socket_send (ezbus_socket_t socket, void *data, size_t size)
ezbus_socket_send() must be sync'ed with ezbus_tranceiver_callback_send() When ezbus_tranceiver_callback_send() is invoked, and consumer has data to send, then consumer should invoke ezbus_socket_send(). Bye return true from ezbus_tranceiver_callback_send(), the consumer signals the desire to have the packet transmitted, otherwise the prepared parcel packet will remain dormant until such time that 'true' is returned by ezbus_tranceiver_callback_send().
int ezbus_socket_recv (ezbus_socket_t socket, void *data, size_t size)
ezbus_socket_recv() must be sync'ed with ezbus_tranceiver_callback_recv() When ezbus_tranceiver_callback_recv() is invoked, and the consumer wishes to receive the data, then the consumer should invoke ezbus_socket_recv() to extract the packet parcel data. Returning true will initiate an ack response to the received parcel packet. otherwise a nack response.
ezbus_socket_t ezbus_socket_open (ezbus_mac_t *mac, ezbus_address_t *peer)
Open a tranceiver channel (socket) with a peer node.
void ezbus_socket_close (ezbus_socket_t socket)
Close a previously opened socket. Once invoked, the socket can no longer be referenced. See also ezbus_socket_open()
bool ezbus_socket_is_open (ezbus_socket_t socket)
Used to determine if a given socket is currently open and available for use.
Function Documentation
bool ezbus_socket_callback_recv (ezbus_socket_t socket)
The consumer of this API is required to implement ezbus_socket_callback_recv(), see ezbus_socket_recv() for details.
Referenced by ezbus_socket_callback_receiver_ready().
bool ezbus_socket_callback_send (ezbus_socket_t socket)
This API implements an interface for using transciever channels to exchange data packets with other ezbus nodes. Such a channel is termed a socket. One socket replresents a signular tranceiver channel between this node, and a single peer. A socket must be 'opened' before it can be used. See ezbus_socket_open() for more details. In the case that an unsolicited parcel packet arrives from a peer (socket==EXBUS_SICKET_ANY), a local socket will automatically be opened prior to ezbus_socket_callback_recv() being invoked. The socket remain opened until closed by the consumer of this API. Be sure to review ezbus_socket_init(), ezbus_socket_callback_send() and ezbus_socket_callback_recv()
The consumer of this API is required to implement ezbus_socket_callback_send(), see ezbus_socket_send() for details.
Referenced by ezbus_socket_callback_transmitter_empty().
void ezbus_socket_close (ezbus_socket_t socket)
Close a previously opened socket. Once invoked, the socket can no longer be referenced. See also ezbus_socket_open()
Definition at line 61 of file ezbus_socket.c.
References ezbus_socket_is_open().
void ezbus_socket_init (void)
Initializes the socket layer, and must be invoked once prior to using any socket functions Invocation must take place from with the thre ad context of the consumer of the API.
Definition at line 41 of file ezbus_socket.c.
References ezbus_platform_memset(), and ezbus_socket_max().
bool ezbus_socket_is_open (ezbus_socket_t socket)
Used to determine if a given socket is currently open and available for use.
Definition at line 70 of file ezbus_socket.c.
References ezbus_socket_mac().
Referenced by ezbus_socket_callback_transmitter_empty(), ezbus_socket_close(), ezbus_socket_rx_packet(), ezbus_socket_rx_seq(), ezbus_socket_set_rx_seq(), ezbus_socket_set_tx_seq(), and ezbus_socket_tx_seq().
ezbus_socket_t ezbus_socket_open (ezbus_mac_t * mac, ezbus_address_t * peer)
Open a tranceiver channel (socket) with a peer node.
Parameters
mac The MAC interface instance to use for this socket connection.
peer The peer node address to connect this socket to.
Returns
A new socket handle, or EZBUS_SOCKET_INVALID if the request could not be successfuly completed. See ezbus_socket_err(). Most likely cause of faulure is that ezbus_socket_count() has reached ezbus_socket_mac(). A finite number of sockets may be open at any one time, as defined by EZBUS_NUM_SOCKETS. When an unsolicited packet arrives when no more sockets are available, the incoming parcel packet is rejected with a 'nack'.
Definition at line 47 of file ezbus_socket.c.
References ezbus_platform_memset(), EZBUS_SOCKET_INVALID, _ezbus_socket_state_t::mac, and _ezbus_socket_state_t::peer.
Referenced by ezbus_socket_callback_receiver_ready().
int ezbus_socket_recv (ezbus_socket_t socket, void * data, size_t size)
ezbus_socket_recv() must be sync'ed with ezbus_tranceiver_callback_recv() When ezbus_tranceiver_callback_recv() is invoked, and the consumer wishes to receive the data, then the consumer should invoke ezbus_socket_recv() to extract the packet parcel data. Returning true will initiate an ack response to the received parcel packet. otherwise a nack response.
Parameters
socket Integer value that references the given socket connection, ezbus_socket_open() The local socket to reply on will be resocketed by invoking ezbus_packet_dst_socket().
data Pointer to the destination storage for received bytes. Storage must be large enough to store size bytes.
size The maximum number of bytes to extract from the parcel packet.
Returns
The number of bytes actually copied to data.
Definition at line 82 of file ezbus_socket.c.
References ezbus_platform_memset(), EZBUS_SOCKET_INVALID, ezbus_socket_mac(), and ezbus_socket_max().
int ezbus_socket_send (ezbus_socket_t socket, void * data, size_t size)
ezbus_socket_send() must be sync'ed with ezbus_tranceiver_callback_send() When ezbus_tranceiver_callback_send() is invoked, and consumer has data to send, then consumer should invoke ezbus_socket_send(). Bye return true from ezbus_tranceiver_callback_send(), the consumer signals the desire to have the packet transmitted, otherwise the prepared parcel packet will remain dormant until such time that 'true' is returned by ezbus_tranceiver_callback_send().
Parameters
socket Integer value that references the given socket connection, ezbus_socket_open()
data Pointer to the data bytes to transmit. May be of arbitrary length, however, all of the data bytes may not be transmitted, see return value for usage suggestion.
size Represents the total nbumber of bytes to send.
Returns
The number of bytes sent. If return is < size and > 0 tis indicates that the transmission was successful, however not all bytes where transmitted. In this case, the consumer may choose to use the return value to continue to transmit the remaining bytes. If 0 is returned, then the socket was unable to transmit the bytes at this time (be sure to synchronize ezbus_tranceiver_send() with ezbus_tranceiver_callback_send() to ensure that it is an appropriate time to populate a transmitter packet. If -1 is returned, then a fault has occured, and () will return the nature of the failure.
Definition at line 76 of file ezbus_socket.c.